package mstc.ws.gob.pe;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WSServiciosHR service = new WSServiciosHR();
 * WSServiciosHRSoap portType = service.getWSServiciosHRSoap();
 * portType.getConductor(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WSServiciosHR", targetNamespace = "http://wshr.mtc.gob.pe/", wsdlLocation = "http://wshr.mtc.gob.pe/wsServiciosHR.asmx?WSDL")
public class WSServiciosHR extends Service {

	private final static URL WSSERVICIOSHR_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(mstc.ws.gob.pe.WSServiciosHR.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = mstc.ws.gob.pe.WSServiciosHR.class.getResource(".");
			url = new URL(baseUrl,
					"http://wshr.mtc.gob.pe/wsServiciosHR.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://wshr.mtc.gob.pe/wsServiciosHR.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WSSERVICIOSHR_WSDL_LOCATION = url;
	}

	public WSServiciosHR(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WSServiciosHR() {
		super(WSSERVICIOSHR_WSDL_LOCATION, new QName("http://wshr.mtc.gob.pe/",
				"WSServiciosHR"));
	}

	/**
	 * 
	 * @return returns WSServiciosHRSoap
	 */
	@WebEndpoint(name = "WSServiciosHRSoap")
	public WSServiciosHRSoap getWSServiciosHRSoap() {
		return super.getPort(new QName("http://wshr.mtc.gob.pe/",
				"WSServiciosHRSoap"), WSServiciosHRSoap.class);
	}

	/**
	 * 
	 * @return returns WSServiciosHRSoap
	 */
	@WebEndpoint(name = "WSServiciosHRSoap12")
	public WSServiciosHRSoap getWSServiciosHRSoap12() {
		return super.getPort(new QName("http://wshr.mtc.gob.pe/",
				"WSServiciosHRSoap12"), WSServiciosHRSoap.class);
	}

}
