package cruzdelsur.ws.com.pe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IServicecruzdelsur", targetNamespace = "http://tempuri.org/")
public interface IServicecruzdelsur {

	/**
	 * 
	 * @param localidadDesembarque
	 * @param fechaProgramacion
	 * @param localidadEmbarque
	 * @return returns cruzdelsur.ws.com.pe.ArrayOfHorario
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/obtenerHorarios")
	@WebResult(name = "obtenerHorariosResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "obtenerHorarios", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.ObtenerHorarios")
	@ResponseWrapper(localName = "obtenerHorariosResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.ObtenerHorariosResponse")
	public ArrayOfHorario obtenerHorarios(
			@WebParam(name = "fechaProgramacion", targetNamespace = "http://tempuri.org/") String fechaProgramacion,
			@WebParam(name = "localidadEmbarque", targetNamespace = "http://tempuri.org/") String localidadEmbarque,
			@WebParam(name = "localidadDesembarque", targetNamespace = "http://tempuri.org/") String localidadDesembarque);

	/**
	 * 
	 * @param agenciaEmbarqueLlave
	 * @param codigoRuta
	 * @param servicioLlave
	 * @param programacionLlave
	 * @param unidadLlave
	 * @param agenciaDesembarqueLlave
	 * @param numeroServicio
	 * @return returns cruzdelsur.ws.com.pe.ArrayOfDistribucion
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/obtenerAsientosDisponibles")
	@WebResult(name = "obtenerAsientosDisponiblesResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "obtenerAsientosDisponibles", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.ObtenerAsientosDisponibles")
	@ResponseWrapper(localName = "obtenerAsientosDisponiblesResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.ObtenerAsientosDisponiblesResponse")
	public ArrayOfDistribucion obtenerAsientosDisponibles(
			@WebParam(name = "codigoRuta", targetNamespace = "http://tempuri.org/") String codigoRuta,
			@WebParam(name = "servicioLlave", targetNamespace = "http://tempuri.org/") String servicioLlave,
			@WebParam(name = "programacionLlave", targetNamespace = "http://tempuri.org/") String programacionLlave,
			@WebParam(name = "numeroServicio", targetNamespace = "http://tempuri.org/") Integer numeroServicio,
			@WebParam(name = "agenciaEmbarqueLlave", targetNamespace = "http://tempuri.org/") String agenciaEmbarqueLlave,
			@WebParam(name = "agenciaDesembarqueLlave", targetNamespace = "http://tempuri.org/") String agenciaDesembarqueLlave,
			@WebParam(name = "unidadLlave", targetNamespace = "http://tempuri.org/") String unidadLlave);

	/**
	 * 
	 * @param codigoRuta
	 * @param nivelUnidad
	 * @param servicioLlave
	 * @param localidadDesembarque
	 * @param programacionLlave
	 * @param codigoAsiento
	 * @param numeroServicio
	 * @param localidadEmbarque
	 * @return returns cruzdelsur.ws.com.pe.ResultBloquearAsiento
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/bloquearAsiento")
	@WebResult(name = "bloquearAsientoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "bloquearAsiento", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.BloquearAsiento")
	@ResponseWrapper(localName = "bloquearAsientoResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.BloquearAsientoResponse")
	public ResultBloquearAsiento bloquearAsiento(
			@WebParam(name = "codigoRuta", targetNamespace = "http://tempuri.org/") String codigoRuta,
			@WebParam(name = "localidadEmbarque", targetNamespace = "http://tempuri.org/") String localidadEmbarque,
			@WebParam(name = "localidadDesembarque", targetNamespace = "http://tempuri.org/") String localidadDesembarque,
			@WebParam(name = "numeroServicio", targetNamespace = "http://tempuri.org/") String numeroServicio,
			@WebParam(name = "programacionLlave", targetNamespace = "http://tempuri.org/") String programacionLlave,
			@WebParam(name = "servicioLlave", targetNamespace = "http://tempuri.org/") String servicioLlave,
			@WebParam(name = "codigoAsiento", targetNamespace = "http://tempuri.org/") String codigoAsiento,
			@WebParam(name = "nivelUnidad", targetNamespace = "http://tempuri.org/") String nivelUnidad);

	/**
	 * 
	 * @param codigoTransaccion
	 * @return returns cruzdelsur.ws.com.pe.ResultDesbloquearAsiento
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/desbloquearAsiento")
	@WebResult(name = "desbloquearAsientoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "desbloquearAsiento", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.DesbloquearAsiento")
	@ResponseWrapper(localName = "desbloquearAsientoResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.DesbloquearAsientoResponse")
	public ResultDesbloquearAsiento desbloquearAsiento(
			@WebParam(name = "codigoTransaccion", targetNamespace = "http://tempuri.org/") String codigoTransaccion);

	/**
	 * 
	 * @param agenciaEmbarqueLlave
	 * @param codigoTransaccion
	 * @param agenciaDesembarqueLlave
	 * @param pasajero
	 * @return returns cruzdelsur.ws.com.pe.ResultVenta
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/venderPasaje")
	@WebResult(name = "venderPasajeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "venderPasaje", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.VenderPasaje")
	@ResponseWrapper(localName = "venderPasajeResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.VenderPasajeResponse")
	public ResultVenta venderPasaje(
			@WebParam(name = "codigoTransaccion", targetNamespace = "http://tempuri.org/") String codigoTransaccion,
			@WebParam(name = "agenciaEmbarqueLlave", targetNamespace = "http://tempuri.org/") String agenciaEmbarqueLlave,
			@WebParam(name = "agenciaDesembarqueLlave", targetNamespace = "http://tempuri.org/") String agenciaDesembarqueLlave,
			@WebParam(name = "pasajero", targetNamespace = "http://tempuri.org/") Pasajero pasajero);

	/**
	 * 
	 * @param serie
	 * @param numero
	 * @return returns cruzdelsur.ws.com.pe.ResultAnularBoleto
	 */
	@WebMethod(action = "http://tempuri.org/IServicecruzdelsur/anularBoleto")
	@WebResult(name = "anularBoletoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "anularBoleto", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.AnularBoleto")
	@ResponseWrapper(localName = "anularBoletoResponse", targetNamespace = "http://tempuri.org/", className = "cruzdelsur.ws.com.pe.AnularBoletoResponse")
	public ResultAnularBoleto anularBoleto(
			@WebParam(name = "serie", targetNamespace = "http://tempuri.org/") String serie,
			@WebParam(name = "numero", targetNamespace = "http://tempuri.org/") String numero);

}
