package mstc.ws.gob.pe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSServiciosHRSoap", targetNamespace = "http://wshr.mtc.gob.pe/")
public interface WSServiciosHRSoap {

	/**
	 * Informacion de Conductor por Empresa de Transporte.
	 * 
	 * @param oConductor
	 * @return returns mstc.ws.gob.pe.ResultConductor
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getConductor")
	@WebResult(name = "getConductorResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getConductor", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetConductor")
	@ResponseWrapper(localName = "getConductorResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetConductorResponse")
	public ResultConductor getConductor(
			@WebParam(name = "oConductor", targetNamespace = "http://wshr.mtc.gob.pe/") Conductor oConductor);

	/**
	 * Informacion de Parametro por Empresa de Transporte.
	 * 
	 * @param oParametro
	 * @return returns mstc.ws.gob.pe.ResultParametro
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getParametro")
	@WebResult(name = "getParametroResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getParametro", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetParametro")
	@ResponseWrapper(localName = "getParametroResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetParametroResponse")
	public ResultParametro getParametro(
			@WebParam(name = "oParametro", targetNamespace = "http://wshr.mtc.gob.pe/") Parametro oParametro);

	/**
	 * Informacion de Vehiculo por Empresa de Transporte.
	 * 
	 * @param oVehiculo
	 * @return returns mstc.ws.gob.pe.ResultVehiculo
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getVehiculo")
	@WebResult(name = "getVehiculoResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getVehiculo", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetVehiculo")
	@ResponseWrapper(localName = "getVehiculoResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.GetVehiculoResponse")
	public ResultVehiculo getVehiculo(
			@WebParam(name = "oVehiculo", targetNamespace = "http://wshr.mtc.gob.pe/") Vehiculo oVehiculo);

	/**
	 * Anulacion de Hoja Ruta por Empresa de Transporte.
	 * 
	 * @param oAnular
	 * @return returns mstc.ws.gob.pe.ResultAnular
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setAnular")
	@WebResult(name = "setAnularResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setAnular", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetAnular")
	@ResponseWrapper(localName = "setAnularResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetAnularResponse")
	public ResultAnular setAnular(
			@WebParam(name = "oAnular", targetNamespace = "http://wshr.mtc.gob.pe/") Anular oAnular);

	/**
	 * Finalizacion de Hoja Ruta por Empresa de Transporte.
	 * 
	 * @param oFinalizar
	 * @return returns mstc.ws.gob.pe.ResultFinalizar
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setFinalizar")
	@WebResult(name = "setFinalizarResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setFinalizar", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetFinalizar")
	@ResponseWrapper(localName = "setFinalizarResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetFinalizarResponse")
	public ResultFinalizar setFinalizar(
			@WebParam(name = "oFinalizar", targetNamespace = "http://wshr.mtc.gob.pe/") Finalizar oFinalizar);

	/**
	 * Registro de Hoja Ruta por Empresa de Transporte.
	 * 
	 * @param oHojaRuta
	 * @return returns mstc.ws.gob.pe.ResultHojaRuta
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setHojaRuta")
	@WebResult(name = "setHojaRutaResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setHojaRuta", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetHojaRuta")
	@ResponseWrapper(localName = "setHojaRutaResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetHojaRutaResponse")
	public ResultHojaRuta setHojaRuta(
			@WebParam(name = "oHojaRuta", targetNamespace = "http://wshr.mtc.gob.pe/") HojaRuta oHojaRuta);

	/**
	 * Registro de Manifiesto por Empresa de Transporte.
	 * 
	 * @param oManifiesto
	 * @return returns mstc.ws.gob.pe.ResultManifiesto
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setManifiesto")
	@WebResult(name = "setManifiestoResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setManifiesto", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetManifiesto")
	@ResponseWrapper(localName = "setManifiestoResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetManifiestoResponse")
	public ResultManifiesto setManifiesto(
			@WebParam(name = "oManifiesto", targetNamespace = "http://wshr.mtc.gob.pe/") Manifiesto oManifiesto);

	/**
	 * Registro de Tripulante por Empresa de Transporte.
	 * 
	 * @param oTripulante
	 * @return returns mstc.ws.gob.pe.ResultTripulante
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setTripulante")
	@WebResult(name = "setTripulanteResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setTripulante", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetTripulante")
	@ResponseWrapper(localName = "setTripulanteResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "mstc.ws.gob.pe.SetTripulanteResponse")
	public ResultTripulante setTripulante(
			@WebParam(name = "oTripulante", targetNamespace = "http://wshr.mtc.gob.pe/") Tripulante oTripulante);

}
