package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoFlota tipoFlota;
	private NumeroFlota numeroFlota;
	private Servicio servicio;
	private Integer empresa;
	private GrupoMantenimiento grupoMantenimiento;
	private String codigo;
	private Double kilRecorridoDia;
	private Double kilAcumuladoOdometro;
	private Double kilAcumuladoEstandar;
	private String numeroPlaca;
	private Integer numeroEjes;
	private String numeroChasis;
	private String numeroMotor;
	private String tarjetaPropiedad;
	private Integer capacidad;
	private Integer anioFabricacion;
	private Integer idnumeroFlota;

	private DocumentoBus documentoBus;
	private ProgramacionServicio programacionServicio;



	private Set<Itinerario> itinerarios = new HashSet<>(0);
	private Set<DocumentoBus> documentoBuses = new HashSet<>(0);
	private Set<Manifiesto> manifiestos = new HashSet<>(0);
	private Set<PuntoControlEstadoBus> puntoControlEstadoBuses = new HashSet<>(0);
	private Set<LiquidacionBus> liquidacionBuses = new HashSet<>(0);
	private Set<ProgramacionServicio> programacionServicios = new HashSet<>(0);


	public Bus() {

	}

	public Bus (Integer id) {
		super();
		this.id = id;
	}

	public Bus (TipoFlota tipoFlota, NumeroFlota numeroFlota, Servicio servicio, Integer empresa, GrupoMantenimiento grupoMantenimiento, String codigo, Double kilRecorridoDia,
			Double kilAcumuladoOdometro, Double kilAcumuladoEstandar, String numeroPlaca, Integer numeroEjes, String numeroChasis, String numeroMotor, String tarjetaPropiedad,
			Integer capacidad, Integer anioFabricacion,
			Set<Itinerario> itinerarios,
			Set<DocumentoBus> documentoBuses,
			Set<Manifiesto> manifiestos,
			Set<PuntoControlEstadoBus> puntoControlEstadoBuses,
			Set<LiquidacionBus> liquidacionBuses,
			Set<ProgramacionServicio> programacionServicios){
		this.tipoFlota = tipoFlota;
		this.numeroFlota = numeroFlota;
		this.servicio = servicio;
		this.empresa = empresa;
		this.grupoMantenimiento = grupoMantenimiento;
		this.codigo = codigo;
		this.kilRecorridoDia = kilRecorridoDia;
		this.kilAcumuladoOdometro = kilAcumuladoOdometro;
		this.kilAcumuladoEstandar = kilAcumuladoEstandar;
		this.numeroPlaca = numeroPlaca;
		this.numeroEjes = numeroEjes;
		this.numeroChasis = numeroChasis;
		this.numeroMotor = numeroMotor;
		this.tarjetaPropiedad = tarjetaPropiedad;
		this.capacidad = capacidad;
		this.anioFabricacion = anioFabricacion;
		this.itinerarios = itinerarios;
		this.documentoBuses = documentoBuses;
		this.manifiestos = manifiestos;
		this.puntoControlEstadoBuses = puntoControlEstadoBuses;
		this.liquidacionBuses = liquidacionBuses;
		this.programacionServicios = programacionServicios;



	}




	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return Objeto tipoFlota.
	 */
	public TipoFlota getTipoFlota() {
		return tipoFlota;
	}
	/**
	 * @param tipoFlota	: Setea el objeto tipoFlota.
	 */
	public void setTipoFlota(TipoFlota tipoFlota) {
		this.tipoFlota = tipoFlota;
	}

	/**
	 * @return Objeto numeroFlota.
	 */
	public NumeroFlota getNumeroFlota() {
		return numeroFlota;
	}
	/**
	 * @param numeroFlota	: Setea el objeto numeroFlota.
	 */
	public void setNumeroFlota(NumeroFlota numeroFlota) {
		this.numeroFlota = numeroFlota;
	}

	/**
	 * @return Objeto servicio.
	 */
	public Servicio getServicio() {
		return servicio;
	}
	/**
	 * @param servicio	: Setea el objeto servicio.
	 */
	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return Objeto empresa.
	 */
	public Integer getEmpresa() {
		return empresa;
	}
	/**
	 * @param empresa	: Setea el objeto empresa.
	 */
	public void setEmpresa(Integer empresa) {
		this.empresa = empresa;
	}

	/**
	 * @return Objeto grupoMantenimiento.
	 */
	public GrupoMantenimiento getGrupoMantenimiento() {
		return grupoMantenimiento;
	}
	/**
	 * @param grupoMantenimiento	: Setea el objeto grupoMantenimiento.
	 */
	public void setGrupoMantenimiento(GrupoMantenimiento grupoMantenimiento) {
		this.grupoMantenimiento = grupoMantenimiento;
	}

	/**
	 * @return Objeto codigo.
	 */
	public String getCodigo() {
		return codigo;
	}
	/**
	 * @param codigo	: Setea el objeto codigo.
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * @return Objeto kilRecorridoDia.
	 */
	public Double getKilRecorridoDia() {
		return kilRecorridoDia;
	}
	/**
	 * @param kilRecorridoDia	: Setea el objeto kilRecorridoDia.
	 */
	public void setKilRecorridoDia(Double kilRecorridoDia) {
		this.kilRecorridoDia = kilRecorridoDia;
	}

	/**
	 * @return Objeto kilAcumuladoOdometro.
	 */
	public Double getKilAcumuladoOdometro() {
		return kilAcumuladoOdometro;
	}
	/**
	 * @param kilAcumuladoOdometro	: Setea el objeto kilAcumuladoOdometro.
	 */
	public void setKilAcumuladoOdometro(Double kilAcumuladoOdometro) {
		this.kilAcumuladoOdometro = kilAcumuladoOdometro;
	}

	/**
	 * @return Objeto kilAcumuladoEstandar.
	 */
	public Double getKilAcumuladoEstandar() {
		return kilAcumuladoEstandar;
	}
	/**
	 * @param kilAcumuladoEstandar	: Setea el objeto kilAcumuladoEstandar.
	 */
	public void setKilAcumuladoEstandar(Double kilAcumuladoEstandar) {
		this.kilAcumuladoEstandar = kilAcumuladoEstandar;
	}

	/**
	 * @return Objeto numeroPlaca.
	 */
	public String getNumeroPlaca() {
		return numeroPlaca;
	}
	/**
	 * @param numeroPlaca	: Setea el objeto numeroPlaca.
	 */
	public void setNumeroPlaca(String numeroPlaca) {
		this.numeroPlaca = numeroPlaca;
	}

	/**
	 * @return Objeto numeroEjes.
	 */
	public Integer getNumeroEjes() {
		return numeroEjes;
	}
	/**
	 * @param numeroEjes	: Setea el objeto numeroEjes.
	 */
	public void setNumeroEjes(Integer numeroEjes) {
		this.numeroEjes = numeroEjes;
	}

	/**
	 * @return Objeto numeroChasis.
	 */
	public String getNumeroChasis() {
		return numeroChasis;
	}
	/**
	 * @param numeroChasis	: Setea el objeto numeroChasis.
	 */
	public void setNumeroChasis(String numeroChasis) {
		this.numeroChasis = numeroChasis;
	}

	/**
	 * @return Objeto numeroMotor.
	 */
	public String getNumeroMotor() {
		return numeroMotor;
	}
	/**
	 * @param numeroMotor	: Setea el objeto numeroMotor.
	 */
	public void setNumeroMotor(String numeroMotor) {
		this.numeroMotor = numeroMotor;
	}

	/**
	 * @return Objeto tarjetaPropiedad.
	 */
	public String getTarjetaPropiedad() {
		return tarjetaPropiedad;
	}
	/**
	 * @param tarjetaPropiedad	: Setea el objeto tarjetaPropiedad.
	 */
	public void setTarjetaPropiedad(String tarjetaPropiedad) {
		this.tarjetaPropiedad = tarjetaPropiedad;
	}

	/**
	 * @return Objeto capacidad.
	 */
	public Integer getCapacidad() {
		return capacidad;
	}
	/**
	 * @param capacidad	: Setea el objeto capacidad.
	 */
	public void setCapacidad(Integer capacidad) {
		this.capacidad = capacidad;
	}

	/**
	 * @return Objeto anioFabricacion.
	 */
	public Integer getAnioFabricacion() {
		return anioFabricacion;
	}
	/**
	 * @param anioFabricacion	: Setea el objeto anioFabricacion.
	 */
	public void setAnioFabricacion(Integer anioFabricacion) {
		this.anioFabricacion = anioFabricacion;
	}

	public Integer getIdnumeroFlota (){
		return idnumeroFlota;
	}

	public void setIdnumeroFlota (Integer idnumeroFlota){
		this.idnumeroFlota=idnumeroFlota;
	}

	public DocumentoBus getDocumentoBus(){
		return  documentoBus;
	}

	public void setDocumentoBus (DocumentoBus documentoBus){
		this.documentoBus=documentoBus;
	}

	public ProgramacionServicio getProgramacionServicio(){
		return programacionServicio;
	}

	public void setProgramacionServicio (ProgramacionServicio programacionServicio){
		this.programacionServicio=programacionServicio;
	}


	/*=======================================================================*/

	public Set<Itinerario> getItinerarios() {
		return this.itinerarios;
	}
	public void setItinerarios(Set<Itinerario> itinerarios) {
		this.itinerarios = itinerarios;
	}

	public Set<DocumentoBus> getDocumentoBuses() {
		return this.documentoBuses;
	}
	public void setDocumentoBuses(Set<DocumentoBus> documentoBuses) {
		this.documentoBuses = documentoBuses;
	}

	public Set<Manifiesto> getManifiestos() {
		return this.manifiestos;
	}
	public void setManifiestos(Set<Manifiesto> manifiestos) {
		this.manifiestos = manifiestos;
	}

	public Set<PuntoControlEstadoBus> getPuntoControlEstadoBuses() {
		return this.puntoControlEstadoBuses;
	}
	public void setPuntoControlEstadoBuses(Set<PuntoControlEstadoBus> puntoControlEstadoBuses) {
		this.puntoControlEstadoBuses = puntoControlEstadoBuses;
	}

	public Set<LiquidacionBus> getLiquidacionBuses() {
		return this.liquidacionBuses;
	}
	public void setLiquidacionBuses(Set<LiquidacionBus> liquidacionBuses) {
		this.liquidacionBuses = liquidacionBuses;
	}

	public Set<ProgramacionServicio> getProgramacionServicios() {
		return this.programacionServicios;
	}
	public void setProgramacionServicios(Set<ProgramacionServicio> programacionServicios) {
		this.programacionServicios = programacionServicios;
	}
}
