package com.cystesoft.vyrbus.model.bean;
// Generated 04/05/2012 12:43:35 PM by Hibernate Tools 3.4.0.CR1


/**
 * Cliente generated by hbm2java
 */
public class Cliente extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Agencia agencia;
	private String numeroDocumento;
	private String razonSocial;
	private String direccion;
	private Ubigeo ubigeo;
	private String contacto;
	private String telefonoFijo;
	private String telefonoFijo2;
	private String email;
	private Double kilometros;
	private String origen;
	private String direccionFacturacion;
	private String rubro;
	private Integer cantidadTrabajadores;
	private String contactoFinaciero;
	private String movil1;
	private String movil2;
	
	private String tipo;									/*NO MAPEADO*/
	private TipoCobranza tipoCobranza;						/*NO MAPEADO*/
	private Double descuento;								/*NO MAPEADO*/
	private LineaCreditoCliente lineaCreditoCliente;		/*NO MAPEADO*/
	private boolean descuentoAutoByCliente=false;			/*No mapeado*/

	public Cliente() {
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the agencia
	 */
	public Agencia getAgencia() {
		return agencia;
	}
	/**
	 * @param agencia the agencia to set
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}
	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}
	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getDireccion() {
		return this.direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getContacto() {
		return this.contacto;
	}
	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}
	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	public String getTelefonoFijo2() {
		return this.telefonoFijo2;
	}
	public void setTelefonoFijo2(String telefonoFijo2) {
		this.telefonoFijo2 = telefonoFijo2;
	}

	public String getEmail() {
		return this.email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	public Double getKilometros() {
		return this.kilometros;
	}
	public void setKilometros(Double kilometros) {
		this.kilometros = kilometros;
	}

	/**
	 * @return Objeto ubigeo.
	 */
	public Ubigeo getUbigeo() {
		return ubigeo;
	}
	/**
	 * @param ubigeo	: Setea el objeto ubigeo.
	 */
	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}
	
	public String getOrigen() {
		return origen;
	}
	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getDireccionFacturacion() {
		return direccionFacturacion;
	}
	public void setDireccionFacturacion(String direccionFacturacion) {
		this.direccionFacturacion = direccionFacturacion;
	}

	public String getTipo() {
		return tipo;
	}
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public TipoCobranza getTipoCobranza() {
		return tipoCobranza;
	}
	public void setTipoCobranza(TipoCobranza tipoCobranza) {
		this.tipoCobranza = tipoCobranza;
	}

	/**
	 * @return the descuento
	 */
	public Double getDescuento() {
		return descuento;
	}
	/**
	 * @param descuento the descuento to set
	 */
	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}
	/**
	 * @return the rubro
	 */
	public String getRubro() {
		return rubro;
	}
	/**
	 * @param rubro the rubro to set
	 */
	public void setRubro(String rubro) {
		this.rubro = rubro;
	}

	/**
	 * @return the cantidadTrabajadores
	 */
	public Integer getCantidadTrabajadores() {
		return cantidadTrabajadores;
	}
	/**
	 * @param cantidadTrabajadores the cantidadTrabajadores to set
	 */
	public void setCantidadTrabajadores(Integer cantidadTrabajadores) {
		this.cantidadTrabajadores = cantidadTrabajadores;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.razonSocial;
	}


	/**
	 * @return the contactoFinaciero
	 */
	public String getContactoFinaciero() {
		return contactoFinaciero;
	}


	/**
	 * @param contactoFinaciero the contactoFinaciero to set
	 */
	public void setContactoFinaciero(String contactoFinaciero) {
		this.contactoFinaciero = contactoFinaciero;
	}


	/**
	 * @return the movil1
	 */
	public String getMovil1() {
		return movil1;
	}


	/**
	 * @param movil1 the movil1 to set
	 */
	public void setMovil1(String movil1) {
		this.movil1 = movil1;
	}


	/**
	 * @return the movil2
	 */
	public String getMovil2() {
		return movil2;
	}


	/**
	 * @param movil2 the movil2 to set
	 */
	public void setMovil2(String movil2) {
		this.movil2 = movil2;
	}


	/**
	 * @return the lineaCreditoCliente
	 */
	public LineaCreditoCliente getLineaCreditoCliente() {
		return lineaCreditoCliente;
	}
	/**
	 * @param lineaCreditoCliente the lineaCreditoCliente to set
	 */
	public void setLineaCreditoCliente(LineaCreditoCliente lineaCreditoCliente) {
		this.lineaCreditoCliente = lineaCreditoCliente;
	}


	/**
	 * @return the descuentoAutoByCliente
	 */
	public boolean isDescuentoAutoByCliente() {
		return descuentoAutoByCliente;
	}


	/**
	 * @param descuentoAutoByCliente the descuentoAutoByCliente to set
	 */
	public void setDescuentoAutoByCliente(boolean descuentoAutoByCliente) {
		this.descuentoAutoByCliente = descuentoAutoByCliente;
	}

}
