package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Concesionario generated by hbm2java
 */
public class Concesionario extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String ruc;
	private String razonSocial;
	private String direccion;
	private Date fechaActivacion;
	private Date fechaCaducidad;
	private Date fechaSuspension;
	private Integer comision;
	private Integer tipoComision;
	private Integer incluyeIgv;

	public Concesionario() {
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id=id;
	}

	public String getRuc() {
		return this.ruc;
	}
	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}
	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public String getDireccion() {
		return this.direccion;
	}
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Date getFechaActivacion() {
		return this.fechaActivacion;
	}
	public void setFechaActivacion(Date fechaActivacion) {
		this.fechaActivacion = fechaActivacion;
	}

	public Date getFechaCaducidad() {
		return this.fechaCaducidad;
	}
	public void setFechaCaducidad(Date fechaCaducidad) {
		this.fechaCaducidad = fechaCaducidad;
	}

	public Date getFechaSuspension() {
		return this.fechaSuspension;
	}
	public void setFechaSuspension(Date fechaSuspension) {
		this.fechaSuspension = fechaSuspension;
	}

	/**
	 * @return the comision
	 */
	public Integer getComision() {
		return comision;
	}

	/**
	 * @param comision the comision to set
	 */
	public void setComision(Integer comision) {
		this.comision = comision;
	}

	/**
	 * @return the tipoComision
	 */
	public Integer getTipoComision() {
		return tipoComision;
	}

	/**
	 * @param tipoComision the tipoComision to set
	 */
	public void setTipoComision(Integer tipoComision) {
		this.tipoComision = tipoComision;
	}

	/**
	 * @return the incluyeIgv
	 */
	public Integer getIncluyeIgv() {
		return incluyeIgv;
	}

	/**
	 * @param incluyeIgv the incluyeIgv to set
	 */
	public void setIncluyeIgv(Integer incluyeIgv) {
		this.incluyeIgv = incluyeIgv;
	}
}
