package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cortesia generated by hbm2java
 */
public class Cortesia extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Pasajero pasajero;
	private TipoFormaPago tipoFormaPago;
	private VentaPasaje ventaPasaje;
	private Personal personal;
	private MotivoCortesia motivoCortesia;
	private Ruta ruta;
	private Date fechaViaje;
	private Date fechaInicio;
	private Date fechaCaducidad;
	private String personaAutoriza;
	private Integer anioCumpleanios;
	private Integer porcentaje;	
	private AutorizadorCortesia autorizadorCortesia;
	private String detalleMotivoCortesia;
	
	private String numeroControl;		//No Mapeado

	public Cortesia() {
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the pasajero
	 */
	public Pasajero getPasajero() {
		return pasajero;
	}
	/**
	 * @param pasajero the pasajero to set
	 */
	public void setPasajero(Pasajero pasajero) {
		this.pasajero = pasajero;
	}

	/**
	 * @return the tipoFormaPago
	 */
	public TipoFormaPago getTipoFormaPago() {
		return tipoFormaPago;
	}
	/**
	 * @param tipoFormaPago the tipoFormaPago to set
	 */
	public void setTipoFormaPago(TipoFormaPago tipoFormaPago) {
		this.tipoFormaPago = tipoFormaPago;
	}

	/**
	 * @return the ventaPasaje
	 */
	public VentaPasaje getVentaPasaje() {
		return ventaPasaje;
	}
	/**
	 * @param ventaPasaje the ventaPasaje to set
	 */
	public void setVentaPasaje(VentaPasaje ventaPasaje) {
		this.ventaPasaje = ventaPasaje;
	}

	/**
	 * @return the personal
	 */
	public Personal getPersonal() {
		return personal;
	}
	/**
	 * @param personal the personal to set
	 */
	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	/**
	 * @return the motivoCortesia
	 */
	public MotivoCortesia getMotivoCortesia() {
		return motivoCortesia;
	}
	/**
	 * @param motivoCortesia the motivoCortesia to set
	 */
	public void setMotivoCortesia(MotivoCortesia motivoCortesia) {
		this.motivoCortesia = motivoCortesia;
	}

	/**
	 * @return the ruta
	 */
	public Ruta getRuta() {
		return ruta;
	}
	/**
	 * @param ruta the ruta to set
	 */
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	/**
	 * @return the fechaViaje
	 */
	public Date getFechaViaje() {
		return fechaViaje;
	}
	/**
	 * @param fechaViaje the fechaViaje to set
	 */
	public void setFechaViaje(Date fechaViaje) {
		this.fechaViaje = fechaViaje;
	}

	/**
	 * @return the fechaInicio
	 */
	public Date getFechaInicio() {
		return fechaInicio;
	}
	/**
	 * @param fechaInicio the fechaInicio to set
	 */
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	/**
	 * @return the fechaCaducidad
	 */
	public Date getFechaCaducidad() {
		return fechaCaducidad;
	}
	/**
	 * @param fechaCaducidad the fechaCaducidad to set
	 */
	public void setFechaCaducidad(Date fechaCaducidad) {
		this.fechaCaducidad = fechaCaducidad;
	}

	/**
	 * @return the personaAutoriza
	 */
	public String getPersonaAutoriza() {
		return personaAutoriza;
	}
	/**
	 * @param personaAutoriza the personaAutoriza to set
	 */
	public void setPersonaAutoriza(String personaAutoriza) {
		this.personaAutoriza = personaAutoriza;
	}

	/**
	 * @return the anioCumpleanios
	 */
	public Integer getAnioCumpleanios() {
		return anioCumpleanios;
	}
	/**
	 * @param anioCumpleanios the anioCumpleanios to set
	 */
	public void setAnioCumpleanios(Integer anioCumpleanios) {
		this.anioCumpleanios = anioCumpleanios;
	}

	/**
	 * @return the porcentaje
	 */
	public Integer getPorcentaje() {
		return porcentaje;
	}
	/**
	 * @param porcentaje the porcentaje to set
	 */
	public void setPorcentaje(Integer porcentaje) {
		this.porcentaje = porcentaje;
	}	
	
	/**
	 * @return then Autorizador cortesia.
	 */
	public AutorizadorCortesia getAutorizadorCortesia(){
		return this.autorizadorCortesia;
	}
	/**
	 * 
	 * @param autorizadorCortesia the autorizadorCortesia to set
	 */
	public void setAutorizadorCortesia(AutorizadorCortesia  autorizadorCortesia){
		this.autorizadorCortesia=autorizadorCortesia;
	}

	/**
	 * @return the numeroControl
	 */
	public String getNumeroControl() {
		return numeroControl;
	}
	/**
	 * @param numeroControl the numeroControl to set
	 */
	public void setNumeroControl(String numeroControl) {
		this.numeroControl = numeroControl;
	}

	/**
	 * @return the detalleMotivoCortesia
	 */
	public String getDetalleMotivoCortesia() {
		return detalleMotivoCortesia;
	}
	/**
	 * @param detalleMotivoCortesia the detalleMotivoCortesia to set
	 */
	public void setDetalleMotivoCortesia(String detalleMotivoCortesia) {
		this.detalleMotivoCortesia = detalleMotivoCortesia;
	}
}
