package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.List;


/**
 * DetalleItinerario generated by hbm2java
 */
public class DetalleItinerario extends GenericBean implements Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Itinerario itinerario;
	private Ruta ruta;
	private Agencia agenciaPartida;
	private Date fechaPartida;
	private String horaPartida;
	private Agencia agenciaLlegada;
	private Date fechaLlegada;
	private String horaLlegada;
	private Double tarifa;
	private Double tarifaLista;
	
	private String asiento;							//No mapeado
	private String piso;							//No mapeado
	private String zona;
	private Boolean esIda;							//No mapeado
	private TarifaFechaAbierta tarifaFechaAbierta; 	//No mapeado	
	
	private Double tarifaSegundoPiso; 				//No Mapeado (Tarifa del Segundo piso - para el caso del Pul "cruz del sur y/o civa")
	private ObjectCruzdelsur objectCruzdelsur;  	//No Mapeado
	private ObjectCiva objectCiva;					//No Mapeado	
	private PoolLocalidad poolLocalidad; 			//No Mapeado - Guarda la localidad destino si es que esta pertence al pool.
	
	private List<ItinerarioAgenciaPartida> lstItinerarioAgenciaPartida;	//No mapeado
	private List<ItinerarioAgenciaLlegada> lstItinerarioAgenciaLlegada;	//No mapeado

	public DetalleItinerario() {
		
	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}


	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}
	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	/**
	 * @return Objeto ruta.
	 */
	public Ruta getRuta() {
		return ruta;
	}
	/**
	 * @param ruta	: Setea el objeto ruta.
	 */
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	/**
	 * @return Objeto agenciaPartida.
	 */
	public Agencia getAgenciaPartida() {
		return agenciaPartida;
	}
	/**
	 * @param agenciaPartida	: Setea el objeto agenciaPartida.
	 */
	public void setAgenciaPartida(Agencia agenciaPartida) {
		this.agenciaPartida = agenciaPartida;
	}

	/**
	 * @return Objeto fechaPartida.
	 */
	public Date getFechaPartida() {
		return fechaPartida;
	}
	/**
	 * @param fechaPartida	: Setea el objeto fechaPartida.
	 */
	public void setFechaPartida(Date fechaPartida) {
		this.fechaPartida = fechaPartida;
	}

	/**
	 * @return Objeto horaPartida.
	 */
	public String getHoraPartida() {
		return horaPartida;
	}
	/**
	 * @param horaPartida	: Setea el objeto horaPartida.
	 */
	public void setHoraPartida(String horaPartida) {
		this.horaPartida = horaPartida;
	}

	/**
	 * @return Objeto agenciaLlegada.
	 */
	public Agencia getAgenciaLlegada() {
		return agenciaLlegada;
	}
	/**
	 * @param agenciaLlegada	: Setea el objeto agenciaLlegada.
	 */
	public void setAgenciaLlegada(Agencia agenciaLlegada) {
		this.agenciaLlegada = agenciaLlegada;
	}

	/**
	 * @return Objeto fechaLlegada.
	 */
	public Date getFechaLlegada() {
		return fechaLlegada;
	}
	/**
	 * @param fechaLlegada	: Setea el objeto fechaLlegada.
	 */
	public void setFechaLlegada(Date fechaLlegada) {
		this.fechaLlegada = fechaLlegada;
	}

	/**
	 * @return Objeto horaLllegada.
	 */
	public String getHoraLlegada() {
		return horaLlegada;
	}
	/**
	 * @param horaLllegada	: Setea el objeto horaLllegada.
	 */
	public void setHoraLlegada(String horaLlegada) {
		this.horaLlegada = horaLlegada;
	}

	/**
	 * @return Objeto tarifa.
	 */
	public Double getTarifa() {
		return tarifa;
	}
	/**
	 * @param tarifa	: Setea el objeto tarifa.
	 */
	public void setTarifa(Double tarifa) {
		this.tarifa = tarifa;
	}

	/**
	 * @return Objeto asiento.
	 */
	public String getAsiento() {
		return asiento;
	}

	/**
	 * @param asiento	: Setea el objeto asiento.
	 */
	public void setAsiento(String asiento) {
		this.asiento = asiento;
	}

	/**
	 * @return the piso
	 */
	public String getPiso() {
		return piso;
	}
	/**
	 * @param piso the piso to set
	 */
	public void setPiso(String piso) {
		this.piso = piso;
	}

	public String getZona() {
		return zona;
	}

	public void setZona(String zona) {
		this.zona = zona;
	}

	/**
	 * @return the esIda
	 */
	public Boolean getEsIda() {
		return esIda;
	}
	/**
	 * @param esIda the esIda to set
	 */
	public void setEsIda(Boolean esIda) {
		this.esIda = esIda;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

	/**
	 * @return the tarifaFechaAbierta
	 */
	public TarifaFechaAbierta getTarifaFechaAbierta() {
		return tarifaFechaAbierta;
	}

	/**
	 * @param tarifaFechaAbierta the tarifaFechaAbierta to set
	 */
	public void setTarifaFechaAbierta(TarifaFechaAbierta tarifaFechaAbierta) {
		this.tarifaFechaAbierta = tarifaFechaAbierta;
	}

	/**
	 * @return the tarifaLista
	 */
	public Double getTarifaLista() {
		return tarifaLista;
	}

	/**
	 * @param tarifaLista the tarifaLista to set
	 */
	public void setTarifaLista(Double tarifaLista) {
		this.tarifaLista = tarifaLista;
	}

	/**
	 * @return the tarifaSegundoPiso
	 */
	public Double getTarifaSegundoPiso() {
		return tarifaSegundoPiso;
	}

	/**
	 * @param tarifaSegundoPiso the tarifaSegundoPiso to set
	 */
	public void setTarifaSegundoPiso(Double tarifaSegundoPiso) {
		this.tarifaSegundoPiso = tarifaSegundoPiso;
	}

	/**
	 * @return the objectCruzdelsur
	 */
	public ObjectCruzdelsur getObjectCruzdelsur() {
		return objectCruzdelsur;
	}

	/**
	 * @param objectCruzdelsur the objectCruzdelsur to set
	 */
	public void setObjectCruzdelsur(ObjectCruzdelsur objectCruzdelsur) {
		this.objectCruzdelsur = objectCruzdelsur;
	}

	/**
	 * @return the objectCiva
	 */
	public ObjectCiva getObjectCiva() {
		return objectCiva;
	}

	/**
	 * @param objectCiva the objectCiva to set
	 */
	public void setObjectCiva(ObjectCiva objectCiva) {
		this.objectCiva = objectCiva;
	}

	/**
	 * @return the poolLocalidad
	 */
	public PoolLocalidad getPoolLocalidad() {
		return poolLocalidad;
	}

	/**
	 * @param poolLocalidad the poolLocalidad to set
	 */
	public void setPoolLocalidad(PoolLocalidad poolLocalidad) {
		this.poolLocalidad = poolLocalidad;
	}

	/**
	 * @return the lstItinerarioAgenciaPartidas
	 */
	public List<ItinerarioAgenciaPartida> getLstItinerarioAgenciaPartida() {
		return lstItinerarioAgenciaPartida;
	}

	/**
	 * @param lstItinerarioAgenciaPartidas the lstItinerarioAgenciaPartidas to set
	 */
	public void setLstItinerarioAgenciaPartida(List<ItinerarioAgenciaPartida> lstItinerarioAgenciaPartida) {
		this.lstItinerarioAgenciaPartida = lstItinerarioAgenciaPartida;
	}

	/**
	 * @return the lstItinerarioAgenciaLlegada
	 */
	public List<ItinerarioAgenciaLlegada> getLstItinerarioAgenciaLlegada() {
		return lstItinerarioAgenciaLlegada;
	}

	/**
	 * @param lstItinerarioAgenciaLlegada the lstItinerarioAgenciaLlegada to set
	 */
	public void setLstItinerarioAgenciaLlegada(List<ItinerarioAgenciaLlegada> lstItinerarioAgenciaLlegada) {
		this.lstItinerarioAgenciaLlegada = lstItinerarioAgenciaLlegada;
	}
}
