package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * DetalleLiquidacion generated by hbm2java
 */
public class DetalleLiquidacion extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Liquidacion liquidacion;
	private Integer anio;
	private TipoFormaPago tipoFormaPago;
	private TipoMovimiento tipoMovimiento;
	private TipoComprobante tipoComprobante;
	private Gasto gasto;
	private Double total;
	private Integer cantidad;

	public DetalleLiquidacion() {
	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return Objeto liquidacion.
	 */
	public Liquidacion getLiquidacion() {
		return liquidacion;
	}

	/**
	 * @param liquidacion	: Setea el objeto liquidacion.
	 */
	public void setLiquidacion(Liquidacion liquidacion) {
		this.liquidacion = liquidacion;
	}

	/**
	 * @return Objeto anio.
	 */
	public Integer getAnio() {
		return anio;
	}

	/**
	 * @param anio	: Setea el objeto anio.
	 */
	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	/**
	 * @return Objeto tipoFormaPago.
	 */
	public TipoFormaPago getTipoFormaPago() {
		return tipoFormaPago;
	}

	/**
	 * @param tipoFormaPago	: Setea el objeto tipoFormaPago.
	 */
	public void setTipoFormaPago(TipoFormaPago tipoFormaPago) {
		this.tipoFormaPago = tipoFormaPago;
	}

	/**
	 * @return Objeto condicionVenta.
	 */
	public TipoMovimiento getTipoMovimiento() {
		return tipoMovimiento;
	}

	/**
	 * @param tipoMovimiento	: Setea el objeto condicionVenta.
	 */
	public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	/**
	 * @return Objeto tipoComprobante.
	 */
	public TipoComprobante getTipoComprobante() {
		return tipoComprobante;
	}

	/**
	 * @param tipoComprobante	: Setea el objeto tipoComprobante.
	 */
	public void setTipoComprobante(TipoComprobante tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	/**
	 * @return Objeto gasto.
	 */
	public Gasto getGasto() {
		return gasto;
	}

	/**
	 * @param gasto	: Setea el objeto gasto.
	 */
	public void setGasto(Gasto gasto) {
		this.gasto = gasto;
	}

	/**
	 * @return Objeto total.
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * @param total	: Setea el objeto total.
	 */
	public void setTotal(Double total) {
		this.total = total;
	}

	/**
	 * @return Objeto cantidad.
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * @param cantidad	: Setea el objeto cantidad.
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	
}
