package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * DocumentoBus generated by hbm2java
 */
public class DocumentoBus extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private EstadoDocumentoBus estadoDocumentoBus;
	private Bus bus;
	private TipoDocumento tipoDocumento;
	private String numeroDocumento;
	private String fechaExpedicion;
	private String fechaVencimiento;
	
	public DocumentoBus() {
	}

	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return Objeto estadoDocumentoBus.
	 */
	public EstadoDocumentoBus getEstadoDocumentoBus() {
		return estadoDocumentoBus;
	}
	/**
	 * @param estadoDocumentoBus	: Setea el objeto estadoDocumentoBus.
	 */
	public void setEstadoDocumentoBus(EstadoDocumentoBus estadoDocumentoBus) {
		this.estadoDocumentoBus = estadoDocumentoBus;
	}

	/**
	 * @return Objeto bus.
	 */
	public Bus getBus() {
		return bus;
	}
	/**
	 * @param bus	: Setea el objeto bus.
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * @return Objeto tipoDocumento.
	 */
	public TipoDocumento getTipoDocumento() {
		return tipoDocumento;
	}
	/**
	 * @param tipoDocumento	: Setea el objeto tipoDocumento.
	 */
	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	/**
	 * @return Objeto numeroDocumento.
	 */
	public String getNumeroDocumento() {
		return numeroDocumento;
	}
	/**
	 * @param numeroDocumento	: Setea el objeto numeroDocumento.
	 */
	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * @return Objeto fechaExpedicion.
	 */
	public String getFechaExpedicion() {
		return fechaExpedicion;
	}
	/**
	 * @param fechaExpedicion	: Setea el objeto fechaExpedicion.
	 */
	public void setFechaExpedicion(String fechaExpedicion) {
		this.fechaExpedicion = fechaExpedicion;
	}

	/**
	 * @return Objeto fechaVencimiento.
	 */
	public String getFechaVencimiento() {
		return fechaVencimiento;
	}
	/**
	 * @param fechaVencimiento	: Setea el objeto fechaVencimiento.
	 */
	public void setFechaVencimiento(String fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}
}
