package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * EspecieValorada generated by hbm2java
 */
public class EspecieValorada extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoComprobante tipoComprobante;
	private Agencia agencia;
	private Integer serie;
	private Long correlativoInicial;
	private Long correlativoFinal;
	private Long correlativoActual;
	private String autorizacionSunat;
	private Double porcentajeUtilizado=.00;
	private Integer formato;
	private String seriefe;
	private String nameSecuenciador;

	private UsuarioHardware usuarioHardware;

	public EspecieValorada() {
		super();
	}

	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return Objeto tipoComprobante.
	 */
	public TipoComprobante getTipoComprobante() {
		return tipoComprobante;
	}

	/**
	 * @param tipoComprobante	: Setea el objeto tipoComprobante.
	 */
	public void setTipoComprobante(TipoComprobante tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	/**
	 * @return Objeto agencia.
	 */
	public Agencia getAgencia() {
		return agencia;
	}

	/**
	 * @param agencia	: Setea el objeto agencia.
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	/**
	 * @return Objeto serie.
	 */
	public Integer getSerie() {
		return serie;
	}

	/**
	 * @param serie	: Setea el objeto serie.
	 */
	public void setSerie(Integer serie) {
		this.serie = serie;
	}

	/**
	 * @return Objeto correlativoInicial.
	 */
	public Long getCorrelativoInicial() {
		return correlativoInicial;
	}

	/**
	 * @param correlativoInicial	: Setea el objeto correlativoInicial.
	 */
	public void setCorrelativoInicial(Long correlativoInicial) {
		this.correlativoInicial = correlativoInicial;
	}

	/**
	 * @return Objeto correlativoFinal.
	 */
	public Long getCorrelativoFinal() {
		return correlativoFinal;
	}

	/**
	 * @param correlativoFinal	: Setea el objeto correlativoFinal.
	 */
	public void setCorrelativoFinal(Long correlativoFinal) {
		this.correlativoFinal = correlativoFinal;
	}

	/**
	 * @return Objeto correlativoActual.
	 */
	public Long getCorrelativoActual() {
		return correlativoActual;
	}

	/**
	 * @param correlativoActual	: Setea el objeto correlativoActual.
	 */
	public void setCorrelativoActual(Long correlativoActual) {
		this.correlativoActual = correlativoActual;
	}

	/**
	 * @return Objeto autorizacionSunat.
	 */
	public String getAutorizacionSunat() {
		return autorizacionSunat;
	}

	/**
	 * @param autorizacionSunat	: Setea el objeto autorizacionSunat.
	 */
	public void setAutorizacionSunat(String autorizacionSunat) {
		this.autorizacionSunat = autorizacionSunat;
	}

	/**
	 * @return the usuarioHardware
	 */
	public UsuarioHardware getUsuarioHardware() {
		return usuarioHardware;
	}
	/**
	 * @param usuarioHardware the usuarioHardware to set
	 */
	public void setUsuarioHardware(UsuarioHardware usuarioHardware) {
		this.usuarioHardware = usuarioHardware;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		Long actual = correlativoActual;
		if(this.seriefe==null){
			Integer serie=this.serie;
			String correlativo = "0000000"+actual;
			String cserie="000"+serie;
			return cserie.substring(cserie.length()-3) + "-"+ correlativo.substring(correlativo.length()-7);
		}else{
			/*para el caso de la fe*/
			String correlativo = "00000000"+actual;
			String cserie=this.seriefe;
			return cserie + "-"+ correlativo.substring(correlativo.length()-8);
		}
	}

	/**
	 * @return the porcentajeUtilizado
	 */
	public Double getPorcentajeUtilizado() {
		return porcentajeUtilizado;
	}

	/**
	 * @param porcentajeUtilizado the porcentajeUtilizado to set
	 */
	public void setPorcentajeUtilizado(Double porcentajeUtilizado) {
		this.porcentajeUtilizado = porcentajeUtilizado;
	}

	/**
	 * @return the formato
	 */
	public Integer getFormato() {
		return formato;
	}

	/**
	 * @param formato the formato to set
	 */
	public void setFormato(Integer formato) {
		this.formato = formato;
	}

	/**
	 * @return the seriefe
	 */
	public String getSeriefe() {
		return seriefe;
	}

	/**
	 * @param seriefe the seriefe to set
	 */
	public void setSeriefe(String seriefe) {
		this.seriefe = seriefe;
	}

	/**
	 * @return the nameSecuenciador
	 */
	public String getNameSecuenciador() {
		return nameSecuenciador;
	}

	/**
	 * @param nameSecuenciador the nameSecuenciador to set
	 */
	public void setNameSecuenciador(String nameSecuenciador) {
		this.nameSecuenciador = nameSecuenciador;
	}
}
