package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

//import java.util.HashSet;
//import java.util.Set;

/**
 * EstadoDocumentoBus generated by hbm2java
 */
public class EstadoDocumentoBus extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private String codigo;
	private Integer tipoEstado;

	//private Set<EstadoDocumentoBus> estadoDocumentoBuses = new HashSet<EstadoDocumentoBus>(0);

	public EstadoDocumentoBus() {
	}

	public EstadoDocumentoBus(Integer id) {
		super();
		this.id = id;
	}

	public EstadoDocumentoBus (String denominacion, String codigo, Integer tipoEstado){
		this.denominacion = denominacion;
		this.codigo = codigo;
		this.tipoEstado = tipoEstado;
	}


	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getCodigo() {
		return this.codigo;
	}
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Integer getTipoEstado() {
		return this.tipoEstado;
	}
	public void setTipoEstado(Integer tipoEstado) {
		this.tipoEstado = tipoEstado;
	}

	/*
	public Set<DocumentoBus> getDocumentoBuses() {
		return this.documentoBuses;
	}
	public void setDocumentoBuses(Set<DocumentoBus> documentoBuses) {
		this.documentoBuses = documentoBuses;
	}
	*/
}
