package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gasto generated by hbm2java
 */
public class Gasto extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoGasto tipoGasto;
	private String numeroDocumento;
	private Double monto;
	private String nombrePiloto;
	private String codigoBus;
	private String consignado;
	private String observacion;
	private String nroCtacte;
	private String horaDeposito;

	//No mapeados
	private Usuario usuario;
	private Date fecha;
	private Agencia agencia;
	private Liquidacion liquidacion;
	private DetalleLiquidacion detalleLiquidacion;
	private LiquidacionOficina liquidacionOficina;
	private Integer cantidad;
	private Set<DetalleLiquidacion> detalleLiquidacions = new HashSet<>(0);
	private Set<LiquidacionOficina> liquidacionOficinas = new HashSet<>(0);

	public Gasto() {
	}

	
	public String getNroCtacte() {
		return nroCtacte;
	}


	public void setNroCtacte(String nroCtacte) {
		this.nroCtacte = nroCtacte;
	}


	public String getHoraDeposito() {
		return horaDeposito;
	}


	public void setHoraDeposito(String horaDeposito) {
		this.horaDeposito = horaDeposito;
	}


	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public TipoGasto getTipoGasto() {
		return this.tipoGasto;
	}
	public void setTipoGasto(TipoGasto tipoGasto) {
		this.tipoGasto = tipoGasto;
	}

	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}
	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public Double getMonto() {
		return this.monto;
	}
	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public String getNombrePiloto() {
		return this.nombrePiloto;
	}
	public void setNombrePiloto(String nombrePiloto) {
		this.nombrePiloto = nombrePiloto;
	}

	public String getCodigoBus() {
		return this.codigoBus;
	}
	public void setCodigoBus(String codigoBus) {
		this.codigoBus = codigoBus;
	}

	public String getConsignado() {
		return this.consignado;
	}
	public void setConsignado(String consignado) {
		this.consignado = consignado;
	}

	public String getObservacion() {
		return this.observacion;
	}
	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Agencia getAgencia(){
		return agencia;
	}

	public void setAgencia(Agencia agencia){
		this.agencia=agencia;
	}

	public Liquidacion getLiquidacion(){
		return liquidacion;
	}

	public void setLiquidacion (Liquidacion liquidacion){
		this.liquidacion=liquidacion;
	}

	public DetalleLiquidacion getDetalleLiquidacion(){
		return detalleLiquidacion;
	}

	public void setDetalleLiquidacion(DetalleLiquidacion detalleLiquidacion){
		this.detalleLiquidacion=detalleLiquidacion;
	}

	public LiquidacionOficina getLiquidacionOficina(){
		return liquidacionOficina;
	}

	public void setLiquidacionOficina(LiquidacionOficina liquidacionOficina){
		this.liquidacionOficina=liquidacionOficina;
	}

	/**
	 * @return the cantidad
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * @param cantidad the cantidad to set
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Set<DetalleLiquidacion> getDetalleLiquidacions() {
		return this.detalleLiquidacions;
	}
	public void setDetalleLiquidacions(
			Set<DetalleLiquidacion> detalleLiquidacions) {
		this.detalleLiquidacions = detalleLiquidacions;
	}

	public Set<LiquidacionOficina> getLiquidacionOficinas() {
		return this.liquidacionOficinas;
	}
	public void setLiquidacionOficinas(
			Set<LiquidacionOficina> liquidacionOficinas) {
		this.liquidacionOficinas = liquidacionOficinas;
	}

	/**
	 * @return the usuario
	 */
	public Usuario getUsuario() {
		return usuario;
	}

	/**
	 * @param usuario the usuario to set
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the fecha
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * @param fecha the fecha to set
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


}
