package com.cystesoft.vyrbus.model.bean;

import java.io.Serializable;

// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * TipoAgencia generated by hbm2java
 */
public class ItinerarioAgenciaLlegada extends GenericBean implements Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private ItinerarioAgenciaLlegadaID itinerarioAgenciaLlegadaID;
	private Itinerario itinerario;
	private Agencia agencia;
	private String horaLlegada;
	private Localidad localidad;
	
	public ItinerarioAgenciaLlegada() {
		
	}
	
	/**
	 * @return Objeto itinerarioAgenciaLlegadaID.
	 */
	public ItinerarioAgenciaLlegadaID getItinerarioAgenciaLlegadaID() {
		return itinerarioAgenciaLlegadaID;
	}
	/**
	 * @param itinerarioAgenciaLlegadaID	: Setea el objeto itinerarioAgenciaLlegadaID.
	 */
	public void setItinerarioAgenciaLlegadaID(ItinerarioAgenciaLlegadaID itinerarioAgenciaLlegadaID) {
		this.itinerarioAgenciaLlegadaID = itinerarioAgenciaLlegadaID;
	}

	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}

	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	/**
	 * @return Objeto agencia.
	 */
	public Agencia getAgencia() {
		return agencia;
	}

	/**
	 * @param agencia	: Setea el objeto agencia.
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	/**
	 * @return Objeto horaLlegada.
	 */
	public String getHoraLlegada() {
		return horaLlegada;
	}

	/**
	 * @param horaLlegada	: Setea el objeto horaLlegada.
	 */
	public void setHoraLlegada(String horaLlegada) {
		this.horaLlegada = horaLlegada;
	}

	/**
	 * @return the localidad
	 */
	public Localidad getLocalidad() {
		return localidad;
	}

	/**
	 * @param localidad the localidad to set
	 */
	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
