package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * TipoAgencia generated by hbm2java
 */
public class ItinerarioAgenciaPartida extends GenericBean implements Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private ItinerarioAgenciaPartidaID itinerarioAgenciaPartidaID;
	private Itinerario itinerario;
	private Agencia agencia;
	private String horaPartida;
	private Localidad localidad;
	
	/**
	 * @return the localidad
	 */
	public Localidad getLocalidad() {
		return localidad;
	}

	/**
	 * @param localidad the localidad to set
	 */
	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	public ItinerarioAgenciaPartida() {
		
	}
	
	/**
	 * @return Objeto itinerarioAgenciaPartidaID.
	 */
	public ItinerarioAgenciaPartidaID getItinerarioAgenciaPartidaID() {
		return itinerarioAgenciaPartidaID;
	}
	/**
	 * @param itinerarioAgenciaPartidaID	: Setea el objeto itinerarioAgenciaPartidaID.
	 */
	public void setItinerarioAgenciaPartidaID(ItinerarioAgenciaPartidaID itinerarioAgenciaPartidaID) {
		this.itinerarioAgenciaPartidaID = itinerarioAgenciaPartidaID;
	}

	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}

	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	/**
	 * @return Objeto agencia.
	 */
	public Agencia getAgencia() {
		return agencia;
	}

	/**
	 * @param agencia	: Setea el objeto agencia.
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	/**
	 * @return Objeto horaPartida.
	 */
	public String getHoraPartida() {
		return horaPartida;
	}

	/**
	 * @param horaPartida	: Setea el objeto horaPartida.
	 */
	public void setHoraPartida(String horaPartida) {
		this.horaPartida = horaPartida;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
}
