package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LiquidacionOficina generated by hbm2java
 */
public class LiquidacionOficina extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Gasto gasto;
	private Liquidacion liquidacion;
	private Integer anio;
	private Date fechaLiquidacion;

	//no mapeado
	private Usuario usuario;
	
	public LiquidacionOficina() {
	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return Objeto gasto.
	 */
	public Gasto getGasto() {
		return gasto;
	}
	/**
	 * @param gasto	: Setea el objeto gasto.
	 */
	public void setGasto(Gasto gasto) {
		this.gasto = gasto;
	}

	/**
	 * @return Objeto liquidacion.
	 */
	public Liquidacion getLiquidacion() {
		return liquidacion;
	}
	/**
	 * @param liquidacion	: Setea el objeto liquidacion.
	 */
	public void setLiquidacion(Liquidacion liquidacion) {
		this.liquidacion = liquidacion;
	}

	/**
	 * @return Objeto anio.
	 */
	public Integer getAnio() {
		return anio;
	}
	/**
	 * @param anio	: Setea el objeto anio.
	 */
	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	/**
	 * @return Objeto fechaLiquidacion.
	 */
	public Date getFechaLiquidacion() {
		return fechaLiquidacion;
	}
	/**
	 * @param fechaLiquidacion	: Setea el objeto fechaLiquidacion.
	 */
	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}
	
	public void setUsuario(Usuario  usuario){
		this.usuario=usuario;
	}
	public Usuario getUsuario(){
		return usuario;
	}
}
