package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;

	private Set<Agencia> agencias = new HashSet<>(0);
	private Set<Ruta> rutasForLocalidadIddestino = new HashSet<>(0);
	private Set<Ruta> rutasForLocalidadIdorigen = new HashSet<>(0);

	public Localidad() {

	}
	/**
	 * @param id
	 */
	public Localidad(Integer id) {
		super();
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}


	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Set<Agencia> getAgencias() {
		return this.agencias;
	}
	public void setAgencias(Set<Agencia> agencias) {
		this.agencias = agencias;
	}

	public Set<Ruta> getRutasForLocalidadIddestino() {
		return this.rutasForLocalidadIddestino;
	}
	public void setRutasForLocalidadIddestino(
			Set<Ruta> rutasForLocalidadIddestino) {
		this.rutasForLocalidadIddestino = rutasForLocalidadIddestino;
	}

	public Set<Ruta> getRutasForLocalidadIdorigen() {
		return this.rutasForLocalidadIdorigen;
	}
	public void setRutasForLocalidadIdorigen(Set<Ruta> rutasForLocalidadIdorigen) {
		this.rutasForLocalidadIdorigen = rutasForLocalidadIdorigen;
	}
}