package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Manifiesto generated by hbm2java
 */
public class Manifiesto extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Itinerario itinerario;
	private Bus bus;
	private String numeroManifiesto;
	private String codigoBus;
	private String piloto;
	private String copiloto;
	private String certificadoHabilitacion;
	private String placa;
	private String autorizacionSunat;
	private String copilotoAuxiliar;
	private String tripulante;
	private Integer mee;
	private Agencia agencia;

	//Variables para la devolucion del ISC
	private String ruc;
	private String per4949;
	private String periodo;
	private String puntoPartidaDepartamento;
	private String puntoPartidaDistrito;
	private String puntoLlegadaDepartamento;
	private String puntoLlegadaDistrito;
	private Double importe;
	private Double importe2;

	/**
	 * @return the ruc
	 */
	public String getRuc() {
		return ruc;
	}

	/**
	 * @param ruc the ruc to set
	 */
	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	/**
	 * @return the per4949
	 */
	public String getPer4949() {
		return per4949;
	}

	/**
	 * @param per4949 the per4949 to set
	 */
	public void setPer4949(String per4949) {
		this.per4949 = per4949;
	}

	/**
	 * @return the periodo
	 */
	public String getPeriodo() {
		return periodo;
	}

	/**
	 * @param periodo the periodo to set
	 */
	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	/**
	 * @return the importe
	 */
	public Double getImporte() {
		return importe;
	}

	/**
	 * @param importe the importe to set
	 */
	public void setImporte(Double importe) {
		this.importe = importe;
	}

	/**
	 * @return the puntoPartidaDepartamento
	 */
	public String getPuntoPartidaDepartamento() {
		return puntoPartidaDepartamento;
	}

	/**
	 * @param puntoPartidaDepartamento the puntoPartidaDepartamento to set
	 */
	public void setPuntoPartidaDepartamento(String puntoPartidaDepartamento) {
		this.puntoPartidaDepartamento = puntoPartidaDepartamento;
	}

	/**
	 * @return the puntoPartidaDistrito
	 */
	public String getPuntoPartidaDistrito() {
		return puntoPartidaDistrito;
	}

	/**
	 * @param puntoPartidaDistrito the puntoPartidaDistrito to set
	 */
	public void setPuntoPartidaDistrito(String puntoPartidaDistrito) {
		this.puntoPartidaDistrito = puntoPartidaDistrito;
	}

	/**
	 * @return the puntoLlegadaDepartamento
	 */
	public String getPuntoLlegadaDepartamento() {
		return puntoLlegadaDepartamento;
	}

	/**
	 * @param puntoLlegadaDepartamento the puntoLlegadaDepartamento to set
	 */
	public void setPuntoLlegadaDepartamento(String puntoLlegadaDepartamento) {
		this.puntoLlegadaDepartamento = puntoLlegadaDepartamento;
	}

	/**
	 * @return the puntoLlegadaDistrito
	 */
	public String getPuntoLlegadaDistrito() {
		return puntoLlegadaDistrito;
	}

	/**
	 * @param puntoLlegadaDistrito the puntoLlegadaDistrito to set
	 */
	public void setPuntoLlegadaDistrito(String puntoLlegadaDistrito) {
		this.puntoLlegadaDistrito = puntoLlegadaDistrito;
	}

	private Set<VentaPasaje> ventaPasajes = new HashSet<>(0);

	public Manifiesto() {
	}

	public Manifiesto(Long id) {
		super();
		this.id = id;
	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}
	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	/**
	 * @return Objeto bus.
	 */
	public Bus getBus() {
		return bus;
	}
	/**
	 * @param bus	: Setea el objeto bus.
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * @return Objeto numeroManifiesto.
	 */
	public String getNumeroManifiesto() {
		return numeroManifiesto;
	}
	/**
	 * @param numeroManifiesto	: Setea el objeto numeroManifiesto.
	 */
	public void setNumeroManifiesto(String numeroManifiesto) {
		this.numeroManifiesto = numeroManifiesto;
	}

	/**
	 * @return Objeto codigoBus.
	 */
	public String getCodigoBus() {
		return codigoBus;
	}
	/**
	 * @param codigoBus	: Setea el objeto codigoBus.
	 */
	public void setCodigoBus(String codigoBus) {
		this.codigoBus = codigoBus;
	}

	/**
	 * @return Objeto piloto.
	 */
	public String getPiloto() {
		return piloto;
	}
	/**
	 * @param piloto	: Setea el objeto piloto.
	 */
	public void setPiloto(String piloto) {
		this.piloto = piloto;
	}

	/**
	 * @return Objeto copiloto.
	 */
	public String getCopiloto() {
		return copiloto;
	}
	/**
	 * @param copiloto	: Setea el objeto copiloto.
	 */
	public void setCopiloto(String copiloto) {
		this.copiloto = copiloto;
	}

	/**
	 * @return Objeto certificadoHabilitacion.
	 */
	public String getCertificadoHabilitacion() {
		return certificadoHabilitacion;
	}
	/**
	 * @param certificadoHabilitacion	: Setea el objeto certificadoHabilitacion.
	 */
	public void setCertificadoHabilitacion(String certificadoHabilitacion) {
		this.certificadoHabilitacion = certificadoHabilitacion;
	}

	/**
	 * @return Objeto placa.
	 */
	public String getPlaca() {
		return placa;
	}
	/**
	 * @param placa	: Setea el objeto placa.
	 */
	public void setPlaca(String placa) {
		this.placa = placa;
	}

	public Set<VentaPasaje> getVentaPasajes() {
		return this.ventaPasajes;
	}
	public void setVentaPasajes(Set<VentaPasaje> ventaPasajes) {
		this.ventaPasajes = ventaPasajes;
	}

	/**
	 * @return the autorizacionSunat
	 */
	public String getAutorizacionSunat() {
		return autorizacionSunat;
	}

	/**
	 * @param autorizacionSunat the autorizacionSunat to set
	 */
	public void setAutorizacionSunat(String autorizacionSunat) {
		this.autorizacionSunat = autorizacionSunat;
	}

	/**
	 * @return the copilotoAuxiliar
	 */
	public String getCopilotoAuxiliar() {
		return copilotoAuxiliar;
	}

	/**
	 * @param copilotoAuxiliar the copilotoAuxiliar to set
	 */
	public void setCopilotoAuxiliar(String copilotoAuxiliar) {
		this.copilotoAuxiliar = copilotoAuxiliar;
	}

	/**
	 * @return the tripulante
	 */
	public String getTripulante() {
		return tripulante;
	}

	/**
	 * @param tripulante the tripulante to set
	 */
	public void setTripulante(String tripulante) {
		this.tripulante = tripulante;
	}

	/**
	 * @return the mee
	 */
	public Integer getMee() {
		return mee;
	}

	/**
	 * @param mee the mee to set
	 */
	public void setMee(Integer mee) {
		this.mee = mee;
	}

	/**
	 * @return the agencia
	 */
	public Agencia getAgencia() {
		return agencia;
	}

	/**
	 * @param agencia the agencia to set
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	/**
	 * @return the importe2
	 */
	public Double getImporte2() {
		return importe2;
	}

	/**
	 * @param importe2 the importe2 to set
	 */
	public void setImporte2(Double importe2) {
		this.importe2 = importe2;
	}


}
