package com.cystesoft.vyrbus.model.bean;

import java.util.List;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * MapaBus generated by hbm2java
 */
public class MapaBus extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
//	private ObjetoBus objetoBus;
	private String pathImagen;
	private Integer tipoObjeto;
	private Servicio servicio;
	private Integer numeroAsiento;
	private Integer numeroFila;
	private Integer numeroColumna;
	private Integer numeroPiso;
//	private TipoAsiento tipoAsiento;
	private Integer numeroZona;


	private List<Integer>listaAsientos;	//No mapeado
	private String rangoAsientos;		//No mapeado
	private TipoPrecio tipoPrecio;		//No mapeado
	private Double precio;				//No mapeado
	private Ruta ruta;					//No mapeado

	public MapaBus() {
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

//	public ObjetoBus getObjetoBus() {
//		return this.objetoBus;
//	}
//	public void setObjetoBus(ObjetoBus objetoBus) {
//		this.objetoBus = objetoBus;
//	}

	public Integer getNumeroZona() {
		return numeroZona;
	}

	public void setNumeroZona(Integer numeroZona) {
		this.numeroZona = numeroZona;
	}

	/**
	 * @return the pathImage
	 */
	public String getPathImagen() {
		return pathImagen;
	}
	/**
	 * @param pathImage the pathImage to set
	 */
	public void setPathImagen(String pathImagen) {
		this.pathImagen = pathImagen;
	}

	/**
	 * @return the tipoObjeto
	 */
	public Integer getTipoObjeto() {
		return tipoObjeto;
	}
	/**
	 * @param tipoObjeto the tipoObjeto to set
	 */
	public void setTipoObjeto(Integer tipoObjeto) {
		this.tipoObjeto = tipoObjeto;
	}

	public Servicio getServicio() {
		return this.servicio;
	}
	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return Objeto numeroAsiento.
	 */
	public Integer getNumeroAsiento() {
		return numeroAsiento;
	}
	/**
	 * @param numeroAsiento	: Setea el objeto numeroAsiento.
	 */
	public void setNumeroAsiento(Integer numeroAsiento) {
		this.numeroAsiento = numeroAsiento;
	}

	public Integer getNumeroFila() {
		return this.numeroFila;
	}
	public void setNumeroFila(Integer numeroFila) {
		this.numeroFila = numeroFila;
	}

	public Integer getNumeroColumna() {
		return this.numeroColumna;
	}
	public void setNumeroColumna(Integer numeroColumna) {
		this.numeroColumna = numeroColumna;
	}

	/**
	 * @return the numeroPiso
	 */
	public Integer getNumeroPiso() {
		return numeroPiso;
	}
	/**
	 * @param numeroPiso the numeroPiso to set
	 */
	public void setNumeroPiso(Integer numeroPiso) {
		this.numeroPiso = numeroPiso;
	}

	/**
	 * @return the tipoAsiento
	 */
//	public TipoAsiento getTipoAsiento() {
//		return tipoAsiento;
//	}
//
//	/**
//	 * @param tipoAsiento the tipoAsiento to set
//	 */
//	public void setTipoAsiento(TipoAsiento tipoAsiento) {
//		this.tipoAsiento = tipoAsiento;
//	}

	/**
	 * @return the listaAsientos
	 */
	public List<Integer> getListaAsientos() {
		return listaAsientos;
	}

	/**
	 * @param listaAsientos the listaAsientos to set
	 */
	public void setListaAsientos(List<Integer> listaAsientos) {
		this.listaAsientos = listaAsientos;
	}

	/**
	 * @return the rangoAsientos
	 */
	public String getRangoAsientos() {
		return rangoAsientos;
	}

	/**
	 * @param rangoAsientos the rangoAsientos to set
	 */
	public void setRangoAsientos(String rangoAsientos) {
		this.rangoAsientos = rangoAsientos;
	}

	/**
	 * @return the tipoPrecio
	 */
	public TipoPrecio getTipoPrecio() {
		return tipoPrecio;
	}

	/**
	 * @param tipoPrecio the tipoPrecio to set
	 */
	public void setTipoPrecio(TipoPrecio tipoPrecio) {
		this.tipoPrecio = tipoPrecio;
	}

	/**
	 * @return the precio
	 */
	public Double getPrecio() {
		return precio;
	}

	/**
	 * @param precio the precio to set
	 */
	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	/**
	 * @return the ruta
	 */
	public Ruta getRuta() {
		return ruta;
	}

	/**
	 * @param ruta the ruta to set
	 */
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}
}
