package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * FormaPago generated by hbm2java
 */
public class MotivoCortesia extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private Integer codigoTitan;
	
	public MotivoCortesia() {
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the denominacion
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion the denominacion to set
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	/**
	 * @return the codigoTitan
	 */
	public Integer getCodigoTitan() {
		return codigoTitan;
	}

	/**
	 * @param codigoTitan the codigoTitan to set
	 */
	public void setCodigoTitan(Integer codigoTitan) {
		this.codigoTitan = codigoTitan;
	}
}
