package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * PreferenciaAlimentaria generated by hbm2java
 */
public class PreferenciaAlimentaria extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	
	private Integer cantidad;							//No mapeado
	private List<VentaPasaje>lstVentaXItinerario;		//No mapeado.
	private Integer tipoConsulta;						//No mapeado.
	private Date fecha;									//No mapeado.
	
	private Set<VentaPasaje> ventaPasajes = new HashSet<VentaPasaje>(0);

	public PreferenciaAlimentaria() {
		super();
	}

	public PreferenciaAlimentaria (Integer id){
		this.id=id;
	}
	
	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Set<VentaPasaje> getVentaPasajes() {
		return this.ventaPasajes;
	}
	public void setVentaPasajes(Set<VentaPasaje> ventaPasajes) {
		this.ventaPasajes = ventaPasajes;
	}

	/**
	 * @return the lstVentaItinerario
	 */
	public List<VentaPasaje> getLstVentaXItinerario() {
		return lstVentaXItinerario;
	}

	/**
	 * @param lstVentaItinerario the lstVentaItinerario to set
	 */
	public void setLstVentaXItinerario(List<VentaPasaje> lstVentaXItinerario) {
		this.lstVentaXItinerario = lstVentaXItinerario;
	}

	/**
	 * @return the cantidad
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * @param cantidad the cantidad to set
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * @return the tipoConsulta
	 */
	public Integer getTipoConsulta() {
		return tipoConsulta;
	}

	/**
	 * @param tipoConsulta the tipoConsulta to set
	 */
	public void setTipoConsulta(Integer tipoConsulta) {
		this.tipoConsulta = tipoConsulta;
	}

	/**
	 * @return the fecha
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * @param fecha the fecha to set
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}
}
