package com.cystesoft.vyrbus.model.bean;

// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * Vrmrol generated by hbm2java
 */
public class Rol extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private Integer nuevo;
	private Integer modificar;
	private Integer grabar;
	private Integer eliminar;
	private Integer consultar;
	private Integer imprimir;
	private Integer exportar;
	private Integer sistema;

	public Rol() {
		super();
	}

	public Rol(Integer id) {
		this.id=id;
	}
	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return Objeto denominacion.
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion	: Setea el objeto denominacion.
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	/**
	 * @return the nuevo
	 */
	public Integer getNuevo() {
		return nuevo;
	}
	/**
	 * @param nuevo the nuevo to set
	 */
	public void setNuevo(Integer nuevo) {
		this.nuevo = nuevo;
	}

	/**
	 * @return the modificar
	 */
	public Integer getModificar() {
		return modificar;
	}
	/**
	 * @param modificar the modificar to set
	 */
	public void setModificar(Integer modificar) {
		this.modificar = modificar;
	}

	/**
	 * @return the grabar
	 */
	public Integer getGrabar() {
		return grabar;
	}
	/**
	 * @param grabar the grabar to set
	 */
	public void setGrabar(Integer grabar) {
		this.grabar = grabar;
	}

	/**
	 * @return the eliminar
	 */
	public Integer getEliminar() {
		return eliminar;
	}
	/**
	 * @param eliminar the eliminar to set
	 */
	public void setEliminar(Integer eliminar) {
		this.eliminar = eliminar;
	}

	/**
	 * @return the consultar
	 */
	public Integer getConsultar() {
		return consultar;
	}
	/**
	 * @param consultar the consultar to set
	 */
	public void setConsultar(Integer consultar) {
		this.consultar = consultar;
	}

	/**
	 * @return the imprimir
	 */
	public Integer getImprimir() {
		return imprimir;
	}
	/**
	 * @param imprimir the imprimir to set
	 */
	public void setImprimir(Integer imprimir) {
		this.imprimir = imprimir;
	}

	/**
	 * @return the exportar
	 */
	public Integer getExportar() {
		return exportar;
	}
	/**
	 * @param exportar the exportar to set
	 */
	public void setExportar(Integer exportar) {
		this.exportar = exportar;
	}

	/**
	 * @return the sistema
	 */
	public Integer getSistema() {
		return sistema;
	}

	/**
	 * @param sistema the sistema to set
	 */
	public void setSistema(Integer sistema) {
		this.sistema = sistema;
	}
}
