package com.cystesoft.vyrbus.model.bean;

// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * Servicio generated by hbm2java
 */
public class Servicio extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String 	denominacion;
	private String 	nombreCorto;
	private Integer numeroPisos;
	private Integer numeroAsientosPiso1;
	private Integer numeroFilasPiso1;
	private Integer numeroColumnasPiso1;
	private Integer numeroAsientosPiso2;
	private Integer numeroFilasPiso2;
	private Integer numeroColumnasPiso2;
	
	//no mapedo
	private Integer numeroServicios;
	private Integer totalAsientos;
	
	
	public Servicio() {
	}
	
	public Servicio(Integer id){
		this.id=id;
	}
	
	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	
	/**
	 * @return Objeto denominacion.
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion	: Setea el objeto denominacion.
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}
	
	/**
	 * @return Objeto nombreCorto.
	 */
	public String getNombreCorto() {
		return nombreCorto;
	}
	/**
	 * @param nombreCorto	: Setea el objeto nombreCorto.
	 */
	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	/**
	 * @return the numeroPisos
	 */
	public Integer getNumeroPisos() {
		return numeroPisos;
	}
	/**
	 * @param numeroPisos the numeroPisos to set
	 */
	public void setNumeroPisos(Integer numeroPisos) {
		this.numeroPisos = numeroPisos;
	}

	/**
	 * @return the numeroAsientosPiso1
	 */
	public Integer getNumeroAsientosPiso1() {
		return numeroAsientosPiso1;
	}
	/**
	 * @param numeroAsientosPiso1 the numeroAsientosPiso1 to set
	 */
	public void setNumeroAsientosPiso1(Integer numeroAsientosPiso1) {
		this.numeroAsientosPiso1 = numeroAsientosPiso1;
	}

	/**
	 * @return the numeroFilasPiso1
	 */
	public Integer getNumeroFilasPiso1() {
		return numeroFilasPiso1;
	}
	/**
	 * @param numeroFilasPiso1 the numeroFilasPiso1 to set
	 */
	public void setNumeroFilasPiso1(Integer numeroFilasPiso1) {
		this.numeroFilasPiso1 = numeroFilasPiso1;
	}

	/**
	 * @return the numeroColumnasPiso1
	 */
	public Integer getNumeroColumnasPiso1() {
		return numeroColumnasPiso1;
	}
	/**
	 * @param numeroColumnasPiso1 the numeroColumnasPiso1 to set
	 */
	public void setNumeroColumnasPiso1(Integer numeroColumnasPiso1) {
		this.numeroColumnasPiso1 = numeroColumnasPiso1;
	}

	/**
	 * @return the numeroAsientosPiso2
	 */
	public Integer getNumeroAsientosPiso2() {
		return numeroAsientosPiso2;
	}
	/**
	 * @param numeroAsientosPiso2 the numeroAsientosPiso2 to set
	 */
	public void setNumeroAsientosPiso2(Integer numeroAsientosPiso2) {
		this.numeroAsientosPiso2 = numeroAsientosPiso2;
	}

	/**
	 * @return the numeroFilasPiso2
	 */
	public Integer getNumeroFilasPiso2() {
		return numeroFilasPiso2;
	}
	/**
	 * @param numeroFilasPiso2 the numeroFilasPiso2 to set
	 */
	public void setNumeroFilasPiso2(Integer numeroFilasPiso2) {
		this.numeroFilasPiso2 = numeroFilasPiso2;
	}

	/**
	 * @return the numeroColumnasPiso2
	 */
	public Integer getNumeroColumnasPiso2() {
		return numeroColumnasPiso2;
	}
	/**
	 * @param numeroColumnasPiso2 the numeroColumnasPiso2 to set
	 */
	public void setNumeroColumnasPiso2(Integer numeroColumnasPiso2) {
		this.numeroColumnasPiso2 = numeroColumnasPiso2;
	}	
	
	/**
	 * @return the getNumeroServicios
	 */
	public Integer getNumeroServicios(){
		return numeroServicios;
	}	
	/**
	 * @param numeroServicios the numeroServicios to set
	 */
	public void setNumeroServicios(Integer numeroServicios){
		this.numeroServicios=numeroServicios;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.denominacion;
	}

	/**
	 * @return the totalAsientos
	 */
	public Integer getTotalAsientos() {
		return totalAsientos;
	}

	/**
	 * @param totalAsientos the totalAsientos to set
	 */
	public void setTotalAsientos(Integer totalAsientos) {
		this.totalAsientos = totalAsientos;
	}
}
