package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

//import java.util.Date;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa extends GenericBean implements java.io.Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private CanalVenta canalVenta;
	private Servicio servicio;
	private Ruta ruta;
	private Integer pisoBus;
	private Integer zonaBus;
//	private Double monto;
//	private Date fechaActivacion;
//	private Date fechaCaducidad;
//	private Date fechaSuspension;

	public Tarifa() {
	}

	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}

//	public Cliente getCliente() {
//		return this.cliente;
//	}
//	public void setCliente(Cliente cliente) {
//		this.cliente = cliente;
//	}
//
	public Ruta getRuta() {
		return this.ruta;
	}
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	public CanalVenta getCanalVenta() {
		return canalVenta;
	}

	public void setCanalVenta(CanalVenta canalVenta) {
		this.canalVenta = canalVenta;
	}

	public Servicio getServicio() {
		return servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	public Integer getPisoBus() {
		return pisoBus;
	}

	public void setPisoBus(Integer pisoBus) {
		this.pisoBus = pisoBus;
	}

	public Integer getZonaBus() {
		return zonaBus;
	}

	public void setZonaBus(Integer zonaBus) {
		this.zonaBus = zonaBus;
	}
	
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

//	public Double getMonto() {
//		return this.monto;
//	}
//	public void setMonto(Double monto) {
//		this.monto = monto;
//	}
//
//	public Date getFechaActivacion() {
//		return this.fechaActivacion;
//	}
//	public void setFechaActivacion(Date fechaActivacion) {
//		this.fechaActivacion = fechaActivacion;
//	}
//
//	public Date getFechaCaducidad() {
//		return this.fechaCaducidad;
//	}
//	public void setFechaCaducidad(Date fechaCaducidad) {
//		this.fechaCaducidad = fechaCaducidad;
//	}
//
//	public Date getFechaSuspension() {
//		return this.fechaSuspension;
//	}
//	public void setFechaSuspension(Date fechaSuspension) {
//		this.fechaSuspension = fechaSuspension;
//	}
}
