package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * TipoComprobante generated by hbm2java
 */
public class TipoComprobante extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private String abreviatura;
	private Integer rubro;
	
	public static final int RUBRO_PASAJES = 1;
	public static final int RUBRO_CARGA = 2;
//	public static final int RUBRO_AMBOS = 3;

	public TipoComprobante() {
	}

	public TipoComprobante(Integer id) {
		super();
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getAbreviatura() {
		return this.abreviatura;
	}
	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	/**
	 * @return Objeto rubro.
	 */
	public Integer getRubro() {
		return rubro;
	}

	/**
	 * @param rubro	: Setea el objeto rubro.
	 */
	public void setRubro(Integer rubro) {
		this.rubro = rubro;
	}
}
