package com.cystesoft.vyrbus.model.bean;

import java.io.Serializable;

// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioHardware generated by hbm2java
 */
public class UsuarioHardware extends GenericBean implements Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Agencia agencia;
	private String direccionMAC;
	private String codigo;
	private String descripcion;
	private CanalVenta canalVenta;
	private Integer printApplet;
	private TitanUsuarioHardware titanUsuarioHardware;
	
	public UsuarioHardware() {
	}
	
	/**
	 * @param id
	 */
	public UsuarioHardware(Integer id) {
		super();
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public Agencia getAgencia() {
		return this.agencia;
	}
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	public CanalVenta getCanalVenta(){
		return this.canalVenta;
	}
	
	public void setCanalVenta(CanalVenta canalVenta){
		this.canalVenta=canalVenta;
	}
	
	/**
	 * @return the direccionMAC
	 */
	public String getDireccionMAC() {
		return direccionMAC;
	}
	/**
	 * @param direccionMAC the direccionMAC to set
	 */
	public void setDireccionMAC(String direccionMAC) {
		this.direccionMAC = direccionMAC;
	}

	public String getCodigo() {
		return this.codigo;
	}
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the printApplet
	 */
	public Integer getPrintApplet() {
		return printApplet;
	}

	/**
	 * @param printApplet the printApplet to set
	 */
	public void setPrintApplet(Integer printApplet) {
		this.printApplet = printApplet;
	}

	/**
	 * @return the titanUsuarioHardware
	 */
	public TitanUsuarioHardware getTitanUsuarioHardware() {
		return titanUsuarioHardware;
	}

	/**
	 * @param titanUsuarioHardware the titanUsuarioHardware to set
	 */
	public void setTitanUsuarioHardware(TitanUsuarioHardware titanUsuarioHardware) {
		this.titanUsuarioHardware = titanUsuarioHardware;
	}
}
