package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioRol generated by hbm2java
 */
public class UsuarioRol extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private UsuarioRolID usuarioRolID;
	private Usuario usuario;
	private Rol rol;

	public UsuarioRol() {
	}

	public UsuarioRol(UsuarioRolID usuarioRolID, Usuario usuario, Rol rol) {
		this.usuarioRolID = usuarioRolID;
		this.rol = rol;
		this.usuario = usuario;
	}

	/**
	 * @return Objeto usuarioRolID.
	 */
	public UsuarioRolID getUsuarioRolID() {
		return usuarioRolID;
	}

	/**
	 * @param usuarioRolID	: Setea el objeto usuarioRolID.
	 */
	public void setUsuarioRolID(UsuarioRolID usuarioRolID) {
		this.usuarioRolID = usuarioRolID;
	}

	/**
	 * @return Objeto usuario.
	 */
	public Usuario getUsuario() {
		return usuario;
	}

	/**
	 * @param usuario	: Setea el objeto usuario.
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return Objeto rol.
	 */
	public Rol getRol() {
		return rol;
	}

	/**
	 * @param rol	: Setea el objeto rol.
	 */
	public void setRol(Rol rol) {
		this.rol = rol;
	}
}
