package com.cystesoft.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

import com.cystesoft.vyrbus.service.fe.Result;

/**
 * VentaPasaje generated by hbm2java
 */
public class VentaPasaje extends GenericBean implements java.io.Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private VentaPasaje ventaPasaje;
	private Long ventaOriginal;
	private Itinerario itinerario;
	private Ruta ruta;
	private Cliente cliente;
	private Pasajero pasajero;
	private FormaPago formaPago;
	private Servicio servicio;
	private TipoComprobante tipoComprobante;
	private TipoMovimiento tipoMovimiento;
	private TipoFormaPago tipoFormaPago;
	private TarjetaCredito tarjetaCredito;
	private Agencia agencia;
	private Agencia agenciaPartida;
	private Agencia agenciaLlegada;
	private Usuario usuario;
	private CanalVenta canalVenta;
	private Manifiesto manifiesto;
	private PreferenciaAlimentaria preferenciaAlimentaria;
	private String numeroBoleto;
	private String numeroBoletoAnterior;
	private Integer numeroAsiento;
	private Integer numeroPiso;
	private String numeroControl;
	private Date fechaPartida;
	private String horaPartida;
	private Date fechaLlegada;
	private String horaLllegada;
	private Integer secuencial;
	private Double tarifa;
	private Double recargo;
	private Double descuento;
	private Double penalidad;
	private Double acuenta;
	private Double importePagado;
	private String tipoTransaccion;
	private Date fechaCaducidad;
	private Liquidacion liquidacion;
	private Date fechaLiquidacion;
	private String numeroOperacionBancaria;
	private Date fechaExpiracionReserva;
	private String horaExpiracionReserva;
	private Integer idaRetorno;
	private String rucClienteCredito;
	private Integer esFechaAbierta;
	private String observaciones;
	private Double importePagadoEfectivo;
	private Double importePagadoTarjeta;
	private Promocion promocion;
	private Long identificadorIdaRetorno;
	private CentroCosto centroCosto;
	private Date fechaTransferencia;
	private String estadoDocumento;
	private TipoMoneda tipoMoneda;
	private Double tipoCambio;
	private Double importePagadoEquibalente;
	private Double descuentoEquibalente;
	private Double tarifaEquibalente;
	private Double igv;
	private TipoNota tipoNota;
	private Integer enviadoSFE;
	private Date fechaEnvioSFE;
	private Double importePagadoByDiferencia;
	
	//No mapeados
	private UsuarioHardware usuarioHardware;
	private List<Integer> subConjunto;
	private Integer cantidadPax;
	private Integer cantidadPaxRuta; 
	private String key;
	private DetalleItinerario detalleItinerario;
	private Boolean servicioEspecialFactura=false;
	private String numeroserie;
	private String ultimoEmitido;
	private Integer numeroBoletoEmitidos;
	private Integer diasTranscurridos;
	private Double promedioXdia;
	private String ultimoEnviadoXAbastecimientos;
	private String fechaUltimoEnvioXAbastecimientos;
	private OperadorTarjetaCredito operadorTarjetaCredito;
	private String numeroVoucher;
	private Integer tipoConsulta;
	private String horaEmbarque;
	private String horaDesembarque;
	private List<VentaPasaje> lstVentaXRuta;
	private List<VentaPasaje> lstPasajeros;	
	private Result result;
	
	private String operadoPor;
	
	/**
	 * Usuario que realiza la Operación Remota
	 */
	private Usuario usuarioRemoto;
	/**
	 * Usuario Hardware desde donde se realiza la Operación Remota
	 */
	private UsuarioHardware usuarioHardwareRemoto;
	private Boolean esRemoto;
	
	
	public VentaPasaje() {
	}
	
	public VentaPasaje(Long id) {
		super();
		this.id = id;
	}
	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}
	
	/**
	 * @return Objeto ventaPasaje.
	 */
	public VentaPasaje getVentaPasaje() {
		return ventaPasaje;
	}
	/**
	 * @param ventaPasaje	: Setea el objeto ventaPasaje.
	 */
	public void setVentaPasaje(VentaPasaje ventaPasaje) {
		this.ventaPasaje = ventaPasaje;
	}
	
	/**
	 * @return the ventaOriginal
	 */
	public Long getVentaOriginal() {
		return ventaOriginal;
	}
	/**
	 * @param ventaOriginal the ventaOriginal to set
	 */
	public void setVentaOriginal(Long ventaOriginal) {
		this.ventaOriginal = ventaOriginal;
	}
	
	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}
	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}
	
	/**
	 * @return Objeto ruta.
	 */
	public Ruta getRuta() {
		return ruta;
	}
	/**
	 * @param ruta	: Setea el objeto ruta.
	 */
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}
	
	/**
	 * @return Objeto cliente.
	 */
	public Cliente getCliente() {
		return cliente;
	}
	/**
	 * @param cliente	: Setea el objeto cliente.
	 */
	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}
	
	/**
	 * @return Objeto pasajero.
	 */
	public Pasajero getPasajero() {
		return pasajero;
	}
	/**
	 * @param pasajero	: Setea el objeto pasajero.
	 */
	public void setPasajero(Pasajero pasajero) {
		this.pasajero = pasajero;
	}
	
	/**
	 * @return Objeto formaPago.
	 */
	public FormaPago getFormaPago() {
		return formaPago;
	}
	/**
	 * @param formaPago	: Setea el objeto formaPago.
	 */
	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}
	
	/**
	 * @return Objeto servicio.
	 */
	public Servicio getServicio() {
		return servicio;
	}
	/**
	 * @param servicio	: Setea el objeto servicio.
	 */
	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}
	
	/**
	 * @return Objeto tipoComprobante.
	 */
	public TipoComprobante getTipoComprobante() {
		return tipoComprobante;
	}
	/**
	 * @param tipoComprobante	: Setea el objeto tipoComprobante.
	 */
	public void setTipoComprobante(TipoComprobante tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}
	
	/**
	 * @return Objeto condicionVenta.
	 */
	public TipoMovimiento getTipoMovimiento() {
		return tipoMovimiento;
	}
	/**
	 * @param tipoMovimiento	: Setea el objeto condicionVenta.
	 */
	public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}
	
	/**
	 * @return Objeto tipoFormaPago.
	 */
	public TipoFormaPago getTipoFormaPago() {
		return tipoFormaPago;
	}
	/**
	 * @param tipoFormaPago	: Setea el objeto tipoFormaPago.
	 */
	public void setTipoFormaPago(TipoFormaPago tipoFormaPago) {
		this.tipoFormaPago = tipoFormaPago;
	}
	
	/**
	 * @return Objeto tarjetaCredito.
	 */
	public TarjetaCredito getTarjetaCredito() {
		return tarjetaCredito;
	}
	/**
	 * @param tarjetaCredito	: Setea el objeto tarjetaCredito.
	 */
	public void setTarjetaCredito(TarjetaCredito tarjetaCredito) {
		this.tarjetaCredito = tarjetaCredito;
	}
	
	/**
	 * @return Objeto agencia.
	 */
	public Agencia getAgencia() {
		return agencia;
	}
	/**
	 * @param agencia	: Setea el objeto agencia.
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}
	
	/**
	 * @return Objeto agenciaPartida.
	 */
	public Agencia getAgenciaPartida() {
		return agenciaPartida;
	}
	/**
	 * @param agenciaPartida	: Setea el objeto agenciaPartida.
	 */
	public void setAgenciaPartida(Agencia agenciaPartida) {
		this.agenciaPartida = agenciaPartida;
	}
	
	/**
	 * @return Objeto agenciaLlegada.
	 */
	public Agencia getAgenciaLlegada() {
		return agenciaLlegada;
	}
	/**
	 * @param agenciaLlegada	: Setea el objeto agenciaLlegada.
	 */
	public void setAgenciaLlegada(Agencia agenciaLlegada) {
		this.agenciaLlegada = agenciaLlegada;
	}
	
	/**
	 * @return Objeto usuario.
	 */
	public Usuario getUsuario() {
		return usuario;
	}
	/**
	 * @param usuario	: Setea el objeto usuario.
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	/**
	 * @return Objeto canalVenta.
	 */
	public CanalVenta getCanalVenta() {
		return canalVenta;
	}
	/**
	 * @param canalVenta	: Setea el objeto canalVenta.
	 */
	public void setCanalVenta(CanalVenta canalVenta) {
		this.canalVenta = canalVenta;
	}
	
	/**
	 * @return Objeto manifiesto.
	 */
	public Manifiesto getManifiesto() {
		return manifiesto;
	}
	/**
	 * @param manifiesto	: Setea el objeto manifiesto.
	 */
	public void setManifiesto(Manifiesto manifiesto) {
		this.manifiesto = manifiesto;
	}
	
	/**
	 * @return Objeto preferenciaAlimentaria.
	 */
	public PreferenciaAlimentaria getPreferenciaAlimentaria() {
		return preferenciaAlimentaria;
	}
	/**
	 * @param preferenciaAlimentaria	: Setea el objeto preferenciaAlimentaria.
	 */
	public void setPreferenciaAlimentaria(
			PreferenciaAlimentaria preferenciaAlimentaria) {
		this.preferenciaAlimentaria = preferenciaAlimentaria;
	}
	
	/**
	 * @return Objeto numeroBoleto.
	 */
	public String getNumeroBoleto() {
		return numeroBoleto;
	}
	/**
	 * @param numeroBoleto	: Setea el objeto numeroBoleto.
	 */
	public void setNumeroBoleto(String numeroBoleto) {
		this.numeroBoleto = numeroBoleto;
	}
	
	/**
	 * @return the numeroBoletoAnterior
	 */
	public String getNumeroBoletoAnterior() {
		return numeroBoletoAnterior;
	}
	/**
	 * @param numeroBoletoAnterior the numeroBoletoAnterior to set
	 */
	public void setNumeroBoletoAnterior(String numeroBoletoAnterior) {
		this.numeroBoletoAnterior = numeroBoletoAnterior;
	}
	
	/**
	 * @return Objeto numeroAsiento.
	 */
	public Integer getNumeroAsiento() {
		return numeroAsiento;
	}
	/**
	 * @param numeroAsiento	: Setea el objeto numeroAsiento.
	 */
	public void setNumeroAsiento(Integer numeroAsiento) {
		this.numeroAsiento = numeroAsiento;
	}
	
	/**
	 * @return the numeroPiso
	 */
	public Integer getNumeroPiso() {
		return numeroPiso;
	}
	/**
	 * @param numeroPiso the numeroPiso to set
	 */
	public void setNumeroPiso(Integer numeroPiso) {
		this.numeroPiso = numeroPiso;
	}
	
	/**
	 * @return the numeroControl
	 */
	public String getNumeroControl() {
		return numeroControl;
	}
	/**
	 * @param numeroControl the numeroControl to set
	 */
	public void setNumeroControl(String numeroControl) {
		this.numeroControl = numeroControl;
	}
	
	/**
	 * @return Objeto fechaPartida.
	 */
	public Date getFechaPartida() {
		return fechaPartida;
	}
	/**
	 * @param fechaPartida	: Setea el objeto fechaPartida.
	 */
	public void setFechaPartida(Date fechaPartida) {
		this.fechaPartida = fechaPartida;
	}
	
	/**
	 * @return Objeto horaPartida.
	 */
	public String getHoraPartida() {
		return horaPartida;
	}
	/**
	 * @param horaPartida	: Setea el objeto horaPartida.
	 */
	public void setHoraPartida(String horaPartida) {
		this.horaPartida = horaPartida;
	}
	
	/**
	 * @return Objeto fechaLlegada.
	 */
	public Date getFechaLlegada() {
		return fechaLlegada;
	}
	/**
	 * @param fechaLlegada	: Setea el objeto fechaLlegada.
	 */
	public void setFechaLlegada(Date fechaLlegada) {
		this.fechaLlegada = fechaLlegada;
	}
	
	/**
	 * @return Objeto horaLllegada.
	 */
	public String getHoraLllegada() {
		return horaLllegada;
	}
	/**
	 * @param horaLllegada	: Setea el objeto horaLllegada.
	 */
	public void setHoraLllegada(String horaLllegada) {
		this.horaLllegada = horaLllegada;
	}
	
	/**
	 * @return Objeto secuencial.
	 */
	public Integer getSecuencial() {
		return secuencial;
	}
	/**
	 * @param secuencial	: Setea el objeto secuencial.
	 */
	public void setSecuencial(Integer secuencial) {
		this.secuencial = secuencial;
	}
	
	/**
	 * @return Objeto tarifa.
	 */
	public Double getTarifa() {
		return tarifa;
	}
	/**
	 * @param tarifa	: Setea el objeto tarifa.
	 */
	public void setTarifa(Double tarifa) {
		this.tarifa = tarifa;
	}
	
	/**
	 * @return Objeto recargo.
	 */
	public Double getRecargo() {
		return recargo;
	}
	/**
	 * @param recargo	: Setea el objeto recargo.
	 */
	public void setRecargo(Double recargo) {
		this.recargo = recargo;
	}
	
	/**
	 * @return Objeto descuento.
	 */
	public Double getDescuento() {
		return descuento;
	}
	/**
	 * @param descuento	: Setea el objeto descuento.
	 */
	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}
	
	/**
	 * @return Objeto penalidad.
	 */
	public Double getPenalidad() {
		return penalidad;
	}
	/**
	 * @param penalidad	: Setea el objeto penalidad.
	 */
	public void setPenalidad(Double penalidad) {
		this.penalidad = penalidad;
	}
	
	/**
	 * @return the acuenta
	 */
	public Double getAcuenta() {
		return acuenta;
	}
	/**
	 * @param acuenta the acuenta to set
	 */
	public void setAcuenta(Double acuenta) {
		this.acuenta = acuenta;
	}
	
	/**
	 * @return Objeto importePagado.
	 */
	public Double getImportePagado() {
		return importePagado;
	}
	/**
	 * @param importePagado	: Setea el objeto importePagado.
	 */
	public void setImportePagado(Double importePagado) {
		this.importePagado = importePagado;
	}
	
	/**
	 * @return Objeto tipoTransaccion.
	 */
	public String getTipoTransaccion() {
		return tipoTransaccion;
	}
	/**
	 * @param tipoTransaccion	: Setea el objeto tipoTransaccion.
	 */
	public void setTipoTransaccion(String tipoTransaccion) {
		this.tipoTransaccion = tipoTransaccion;
	}
	
	/**
	 * @return Objeto fechaCaducidad.
	 */
	public Date getFechaCaducidad() {
		return fechaCaducidad;
	}
	/**
	 * @param fechaCaducidad	: Setea el objeto fechaCaducidad.
	 */
	public void setFechaCaducidad(Date fechaCaducidad) {
		this.fechaCaducidad = fechaCaducidad;
	}
	
	/**
	 * @return the liquidacion
	 */
	public Liquidacion getLiquidacion() {
		return liquidacion;
	}
	/**
	 * @param liquidacion the liquidacion to set
	 */
	public void setLiquidacion(Liquidacion liquidacion) {
		this.liquidacion = liquidacion;
	}
	
	/**
	 * @return Objeto fechaLiquidacion.
	 */
	public Date getFechaLiquidacion() {
		return fechaLiquidacion;
	}
	/**
	 * @param fechaLiquidacion	: Setea el objeto fechaLiquidacion.
	 */
	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}
	
	/**
	 * @return Objeto numeroOperacionBancaria.
	 */
	public String getNumeroOperacionBancaria() {
		return numeroOperacionBancaria;
	}
	/**
	 * @param numeroOperacionBancaria	: Setea el objeto numeroOperacionBancaria.
	 */
	public void setNumeroOperacionBancaria(String numeroOperacionBancaria) {
		this.numeroOperacionBancaria = numeroOperacionBancaria;
	}
	
	/**
	 * @return Objeto fechaExpiracionReserva.
	 */
	public Date getFechaExpiracionReserva() {
		return fechaExpiracionReserva;
	}
	/**
	 * @param fechaExpiracionReserva	: Setea el objeto fechaExpiracionReserva.
	 */
	public void setFechaExpiracionReserva(Date fechaExpiracionReserva) {
		this.fechaExpiracionReserva = fechaExpiracionReserva;
	}
	
	/**
	 * @return Objeto horaExpiracionReserva.
	 */
	public String getHoraExpiracionReserva() {
		return horaExpiracionReserva;
	}
	/**
	 * @param horaExpiracionReserva	: Setea el objeto horaExpiracionReserva.
	 */
	public void setHoraExpiracionReserva(String horaExpiracionReserva) {
		this.horaExpiracionReserva = horaExpiracionReserva;
	}
	
	/**
	 * @return the idaRetorno
	 */
	public Integer getIdaRetorno() {
		return idaRetorno;
	}
	/**
	 * @param idaRetorno the idaRetorno to set
	 */
	public void setIdaRetorno(Integer idaRetorno) {
		this.idaRetorno = idaRetorno;
	}
	
	/**
	 * @return the rucClienteCredito
	 */
	public String getRucClienteCredito() {
		return rucClienteCredito;
	}
	/**
	 * @param rucClienteCredito the rucClienteCredito to set
	 */
	public void setRucClienteCredito(String rucClienteCredito) {
		this.rucClienteCredito = rucClienteCredito;
	}
	
	/**
	 * @return the esAbierta
	 */
	public Integer getEsFechaAbierta() {
		return esFechaAbierta;
	}
	/**
	 * @param esAbierta the esAbierta to set
	 */
	public void setEsFechaAbierta(Integer esFechaAbierta) {
		this.esFechaAbierta = esFechaAbierta;
	}
	
	/**
	 * @return the observaciones
	 */
	public String getObservaciones() {
		return observaciones;
	}
	/**
	 * @param observaciones the observaciones to set
	 */
	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
	
	/**
	 * @return the importePagadoEfectivo
	 */
	public Double getImportePagadoEfectivo() {
		return importePagadoEfectivo;
	}
	/**
	 * @param importePagadoEfectivo the importePagadoEfectivo to set
	 */
	public void setImportePagadoEfectivo(Double importePagadoEfectivo) {
		this.importePagadoEfectivo = importePagadoEfectivo;
	}
	
	/**
	 * @return the importePagadoTarjeta
	 */
	public Double getImportePagadoTarjeta() {
		return importePagadoTarjeta;
	}
	/**
	 * @param importePagadoTarjeta the importePagadoTarjeta to set
	 */
	public void setImportePagadoTarjeta(Double importePagadoTarjeta) {
		this.importePagadoTarjeta = importePagadoTarjeta;
	}
	
	/**
	 * @return the promocion
	 */
	public Promocion getPromocion() {
		return promocion;
	}
	/**
	 * @param promocion the promocion to set
	 */
	public void setPromocion(Promocion promocion) {
		this.promocion = promocion;
	}
	
	/**
	 * @return the identificadorIdaRetorno
	 */
	public Long getIdentificadorIdaRetorno() {
		return identificadorIdaRetorno;
	}
	/**
	 * @param identificadorIdaRetorno the identificadorIdaRetorno to set
	 */
	public void setIdentificadorIdaRetorno(Long identificadorIdaRetorno) {
		this.identificadorIdaRetorno = identificadorIdaRetorno;
	}
	
	/**
	 * @return the usuarioHardware
	 */
	public UsuarioHardware getUsuarioHardware() {
		return usuarioHardware;
	}
	/**
	 * @param usuarioHardware the usuarioHardware to set
	 */
	public void setUsuarioHardware(UsuarioHardware usuarioHardware) {
		this.usuarioHardware = usuarioHardware;
	}
	
	/**
	 * @return cantidadpax
	 */
	public  Integer getCantidadPax(){
		return cantidadPax;
	}
	
	/**
	 * @param cantidadPax: cantidad de pasajeros
	 */
	public void setCantidadPax(Integer cantidadPax){
		this.cantidadPax=cantidadPax;
	}
	
	/**
	 * @return the subConjunto
	 */
	public List<Integer> getSubConjunto() {
		return subConjunto;
	}
	/**
	 * @param subConjunto the subConjunto to set
	 */
	public void setSubConjunto(List<Integer> subConjunto) {
		this.subConjunto = subConjunto;
	}
	
	/**
	 * Clave con el siguiente formato <b>nAsiento-nPiso
	 * @return the key
	 */
	public String getKey() {
		return key;
	}
	/**
	 * Setea el formato de la clave <b>nAsiento-nPiso
	 * @param key the key to set
	 */
	public void setKey() {
		this.key = this.numeroAsiento+"-"+this.numeroPiso;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
	/**
	 * @return the detalleItinerario
	 */
	public DetalleItinerario getDetalleItinerario() {
		return detalleItinerario;
	}
	/**
	 * @param detalleItinerario the detalleItinerario to set
	 */
	public void setDetalleItinerario(DetalleItinerario detalleItinerario) {
		this.detalleItinerario = detalleItinerario;
	}
	/**
	 * @return the servicioEspecialFactura
	 */
	public Boolean getServicioEspecialFactura() {
		return servicioEspecialFactura;
	}
	/**
	 * @param servicioEspecialFactura the servicioEspecialFactura to set
	 */
	public void setServicioEspecialFactura(Boolean servicioEspecialFactura) {
		this.servicioEspecialFactura = servicioEspecialFactura;
	}
	/**
	 * @return the serie
	 */
	public String getNumeroSerie() {
		return numeroserie;
	}
	/**
	 * @param serie the serie to set
	 */
	public void setNumeroSerie(String numeroSerie) {
		this.numeroserie = numeroSerie;
	}
	/**
	 * @return the ultimoEmitido
	 */
	public String getUltimoEmitido() {
		return ultimoEmitido;
	}
	/**
	 * @param ultimoEmitido the ultimoEmitido to set
	 */
	public void setUltimoEmitido(String ultimoEmitido) {
		this.ultimoEmitido = ultimoEmitido;
	}
	/**
	 * @return the numeroBoletoEmitidos
	 */
	public Integer getNumeroBoletoEmitidos() {
		return numeroBoletoEmitidos;
	}
	/**
	 * @param numeroBoletoEmitidos the numeroBoletoEmitidos to set
	 */
	public void setNumeroBoletoEmitidos(Integer numeroBoletoEmitidos) {
		this.numeroBoletoEmitidos = numeroBoletoEmitidos;
	}
	/**
	 * @return the diasTranscurridos
	 */
	public Integer getDiasTranscurridos() {
		return diasTranscurridos;
	}
	/**
	 * @param diasTranscurridos the diasTranscurridos to set
	 */
	public void setDiasTranscurridos(Integer diasTranscurridos) {
		this.diasTranscurridos = diasTranscurridos;
	}
	/**
	 * @return the promedioXdia
	 */
	public Double getPromedioXdia() {
		return promedioXdia;
	}
	/**
	 * @param promedioXdia the promedioXdia to set
	 */
	public void setPromedioXdia(Double promedioXdia) {
		this.promedioXdia = promedioXdia;
	}
	/**
	 * @return the ultimoEnviadoXAbastecimientos
	 */
	public String getUltimoEnviadoXAbastecimientos() {
		return ultimoEnviadoXAbastecimientos;
	}
	/**
	 * @param ultimoEnviadoXAbastecimientos the ultimoEnviadoXAbastecimientos to set
	 */
	public void setUltimoEnviadoXAbastecimientos(String ultimoEnviadoXAbastecimientos) {
		this.ultimoEnviadoXAbastecimientos = ultimoEnviadoXAbastecimientos;
	}
	/**
	 * @return the fechaUltimoEnvioXAbastecimientos
	 */
	public String getFechaUltimoEnvioXAbastecimientos() {
		return fechaUltimoEnvioXAbastecimientos;
	}
	/**
	 * @param fechaUltimoEnvioXAbastecimientos the fechaUltimoEnvioXAbastecimientos to set
	 */
	public void setFechaUltimoEnvioXAbastecimientos(String fechaUltimoEnvioXAbastecimientos) {
		this.fechaUltimoEnvioXAbastecimientos = fechaUltimoEnvioXAbastecimientos;
	}
	/**
	 * @return the operadorTarjetaCredito
	 */
	public OperadorTarjetaCredito getOperadorTarjetaCredito() {
		return operadorTarjetaCredito;
	}
	/**
	 * @param operadorTarjetaCredito the operadorTarjetaCredito to set
	 */
	public void setOperadorTarjetaCredito(OperadorTarjetaCredito operadorTarjetaCredito) {
		this.operadorTarjetaCredito = operadorTarjetaCredito;
	}
	/**
	 * @return the centroCosto
	 */
	public CentroCosto getCentroCosto() {
		return centroCosto;
	}
	/**
	 * @param centroCosto the centroCosto to set
	 */
	public void setCentroCosto(CentroCosto centroCosto) {
		this.centroCosto = centroCosto;
	}
	/**
	 * @return the numeroVoucher
	 */
	public String getNumeroVoucher() {
		return numeroVoucher;
	}
	/**
	 * @param numeroVoucher the numeroVoucher to set
	 */
	public void setNumeroVoucher(String numeroVoucher) {
		this.numeroVoucher = numeroVoucher;
	}
	/**
	 * @return the cantidadPaxRuta
	 */
	public Integer getCantidadPaxRuta() {
		return cantidadPaxRuta;
	}
	/**
	 * @param cantidadPaxRuta the cantidadPaxRuta to set
	 */
	public void setCantidadPaxRuta(Integer cantidadPaxRuta) {
		this.cantidadPaxRuta = cantidadPaxRuta;
	}
	/**
	 * @return the tipoConsulta
	 */
	public Integer getTipoConsulta() {
		return tipoConsulta;
	}
	/**
	 * @param tipoConsulta the tipoConsulta to set
	 */
	public void setTipoConsulta(Integer tipoConsulta) {
		this.tipoConsulta = tipoConsulta;
	}
	/**
	 * @return the horaEmbarque
	 */
	public String getHoraEmbarque() {
		return horaEmbarque;
	}
	/**
	 * @param horaEmbarque the horaEmbarque to set
	 */
	public void setHoraEmbarque(String horaEmbarque) {
		this.horaEmbarque = horaEmbarque;
	}
	/**
	 * @return the horaDesembarque
	 */
	public String getHoraDesembarque() {
		return horaDesembarque;
	}
	/**
	 * @param horaDesembarque the horaDesembarque to set
	 */
	public void setHoraDesembarque(String horaDesembarque) {
		this.horaDesembarque = horaDesembarque;
	}
	/**
	 * @return Usuario que realiza la Operación Remota
	 */
	public Usuario getUsuarioRemoto() {
		return usuarioRemoto;
	}
	/**
	 * @param usuarioRemoto the usuarioRemoto to set
	 */
	public void setUsuarioRemoto(Usuario usuarioRemoto) {
		this.usuarioRemoto = usuarioRemoto;
	}
	/**
	 * @return Usuario Hardware desde donde se realiza la Operación Remota
	 */
	public UsuarioHardware getUsuarioHardwareRemoto() {
		return usuarioHardwareRemoto;
	}
	/**
	 * @param usuarioHardwareRemoto the usuarioHardwareRemoto to set
	 */
	public void setUsuarioHardwareRemoto(UsuarioHardware usuarioHardwareRemoto) {
		this.usuarioHardwareRemoto = usuarioHardwareRemoto;
	}

	/**
	 * @return the esRemoto
	 */
	public Boolean getEsRemoto() {
		return esRemoto;
	}

	/**
	 * @param esRemoto the esRemoto to set
	 */
	public void setEsRemoto(Boolean esRemoto) {
		this.esRemoto = esRemoto;
	}

	/**
	 * @return the lstVentaRuta
	 */
	public List<VentaPasaje> getLstVentaXRuta() {
		return lstVentaXRuta;
	}

	/**
	 * @param lstVentaRuta the lstVentaRuta to set
	 */
	public void setLstVentaXRuta(List<VentaPasaje> lstVentaXRuta) {
		this.lstVentaXRuta = lstVentaXRuta;
	}

	/**
	 * @return the fechaTransferencia
	 */
	public Date getFechaTransferencia() {
		return fechaTransferencia;
	}

	/**
	 * @param fechaTransferencia the fechaTransferencia to set
	 */
	public void setFechaTransferencia(Date fechaTransferencia) {
		this.fechaTransferencia = fechaTransferencia;
	}

	/**
	 * @return the lstPasajeros
	 */
	public List<VentaPasaje> getLstPasajeros() {
		return lstPasajeros;
	}

	/**
	 * @param lstPasajeros the lstPasajeros to set
	 */
	public void setLstPasajeros(List<VentaPasaje> lstPasajeros) {
		this.lstPasajeros = lstPasajeros;
	}

	/**
	 * @return the estadoDocumento
	 */
	public String getEstadoDocumento() {
		return estadoDocumento;
	}

	/**
	 * @param estadoDocumento the estadoDocumento to set
	 */
	public void setEstadoDocumento(String estadoDocumento) {
		this.estadoDocumento = estadoDocumento;
	}

	/**
	 * @return the tipoMoneda
	 */
	public TipoMoneda getTipoMoneda() {
		return tipoMoneda;
	}

	/**
	 * @param tipoMoneda the tipoMoneda to set
	 */
	public void setTipoMoneda(TipoMoneda tipoMoneda) {
		this.tipoMoneda = tipoMoneda;
	}

	/**
	 * @return the tipoCambio
	 */
	public Double getTipoCambio() {
		return tipoCambio;
	}

	/**
	 * @param tipoCambio the tipoCambio to set
	 */
	public void setTipoCambio(Double tipoCambio) {
		this.tipoCambio = tipoCambio;
	}

	/**
	 * @return the importePagadoEquibalente
	 */
	public Double getImportePagadoEquibalente() {
		return importePagadoEquibalente;
	}

	/**
	 * @param importePagadoEquibalente the importePagadoEquibalente to set
	 */
	public void setImportePagadoEquibalente(Double importePagadoEquibalente) {
		this.importePagadoEquibalente = importePagadoEquibalente;
	}

	/**
	 * @return the descuentoEquibalente
	 */
	public Double getDescuentoEquibalente() {
		return descuentoEquibalente;
	}

	/**
	 * @param descuentoEquibalente the descuentoEquibalente to set
	 */
	public void setDescuentoEquibalente(Double descuentoEquibalente) {
		this.descuentoEquibalente = descuentoEquibalente;
	}

	/**
	 * @return the tarifaEquibalente
	 */
	public Double getTarifaEquibalente() {
		return tarifaEquibalente;
	}

	/**
	 * @param tarifaEquibalente the tarifaEquibalente to set
	 */
	public void setTarifaEquibalente(Double tarifaEquibalente) {
		this.tarifaEquibalente = tarifaEquibalente;
	}

	/**
	 * @return the operadoPor
	 */
	public String getOperadoPor() {
		return operadoPor;
	}

	/**
	 * @param operadoPor the operadoPor to set
	 */
	public void setOperadoPor(String operadoPor) {
		this.operadoPor = operadoPor;
	}

	/**
	 * @return the igv
	 */
	public Double getIgv() {
		return igv;
	}

	/**
	 * @param igv the igv to set
	 */
	public void setIgv(Double igv) {
		this.igv = igv;
	}

	/**
	 * @return the tipoNota
	 */
	public TipoNota getTipoNota() {
		return tipoNota;
	}

	/**
	 * @param tipoNota the tipoNota to set
	 */
	public void setTipoNota(TipoNota tipoNota) {
		this.tipoNota = tipoNota;
	}

	/**
	 * @return the enviadoSFE
	 */
	public Integer getEnviadoSFE() {
		return enviadoSFE;
	}

	/**
	 * @param enviadoSFE the enviadoSFE to set
	 */
	public void setEnviadoSFE(Integer enviadoSFE) {
		this.enviadoSFE = enviadoSFE;
	}

	/**
	 * @return the fechaEnvioSFE
	 */
	public Date getFechaEnvioSFE() {
		return fechaEnvioSFE;
	}

	/**
	 * @param fechaEnvioSFE the fechaEnvioSFE to set
	 */
	public void setFechaEnvioSFE(Date fechaEnvioSFE) {
		this.fechaEnvioSFE = fechaEnvioSFE;
	}

	/**
	 * @return the result
	 */
	public Result getResult() {
		return result;
	}

	/**
	 * @param result the result to set
	 */
	public void setResult(Result result) {
		this.result = result;
	}

	/**
	 * @return the importePagadoByDiferencia
	 */
	public Double getImportePagadoByDiferencia() {
		return importePagadoByDiferencia;
	}

	/**
	 * @param importePagadoByDiferencia the importePagadoByDiferencia to set
	 */
	public void setImportePagadoByDiferencia(Double importePagadoByDiferencia) {
		this.importePagadoByDiferencia = importePagadoByDiferencia;
	}
}
