package pe.itsb.vyrbus.model.bean;


// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * Agencia generated by hbm2java
 */
public class Agencia extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoAgencia tipoAgencia;
	private Concesionario concesionario;
	private Localidad localidad;
	private String denominacion;
	private String nombreCorto;
	private Boolean esTerminal;
	private Ubigeo ubigeo;
	private String direccion;
	private String codigo;
	private Nacionalidad nacionalidad;
//	private TipoMoneda tipoMoneda;


	//No mapeado
	private Usuario usuario;
	private String horaPartida;		// Mapeado para las Agencias por Itinerario Itinerarios_AgPartida, Itinerarios_AgLlegada




	public Agencia() {
	}

	/**
	 * @param id
	 */
	public Agencia(Integer id) {
		super();
		this.id = id;
	}

	public Agencia(TipoAgencia tipoAgencia, Concesionario concesionario,Localidad localidad,
			String denominacion, String nombreCorto,Boolean esTerminal) {
		this.tipoAgencia = tipoAgencia;
		this.concesionario = concesionario;
		this.localidad = localidad;
		this.denominacion = denominacion;
		this.nombreCorto = nombreCorto;
		this.esTerminal = esTerminal;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the tipoAgencia
	 */
	public TipoAgencia getTipoAgencia() {
		return tipoAgencia;
	}
	/**
	 * @param tipoAgencia the tipoAgencia to set
	 */
	public void setTipoAgencia(TipoAgencia tipoAgencia) {
		this.tipoAgencia = tipoAgencia;
	}

	/**
	 * @return the concesionario
	 */
	public Concesionario getConcesionario() {
		return concesionario;
	}
	/**
	 * @param concesionario the concesionario to set
	 */
	public void setConcesionario(Concesionario concesionario) {
		this.concesionario = concesionario;
	}

	/**
	 * @return the localidad
	 */
	public Localidad getLocalidad() {
		return localidad;
	}
	/**
	 * @param localidad the localidad to set
	 */
	public void setLocalidad(Localidad localidad) {
		this.localidad = localidad;
	}

	/**
	 * @return the denominacion
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion the denominacion to set
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	/**
	 * @return the nombreCorto
	 */
	public String getNombreCorto() {
		return nombreCorto;
	}
	/**
	 * @param nombreCorto the nombreCorto to set
	 */
	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	/**
	 * @return the esTerminal
	 */
	public Boolean getEsTerminal() {
		return esTerminal;
	}
	/**
	 * @param esTerminal the esTerminal to set
	 */
	public void setEsTerminal(Boolean esTerminal) {
		this.esTerminal = esTerminal;
	}

	/**
	 * @return the ubigeo
	 */
	public Ubigeo getUbigeo() {
		return ubigeo;
	}
	/**
	 * @param ubigeo the ubigeo to set
	 */
	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	/**
	 * @return the horaPartida
	 */
	public String getHoraPartida() {
		return horaPartida;
	}
	/**
	 * @param horaPartida the horaPartida to set
	 */
	public void setHoraPartida(String horaPartida) {
		this.horaPartida = horaPartida;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.denominacion;
	}

	/**
	 * @return the direccion
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * @param direccion the direccion to set
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * @return the codigo
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * @param codigo the codigo to set
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	/**
	 * @return the usuarios
	 */
	public Usuario getUsuario() {
		return usuario;
	}

	/**
	 * @param usuarios the usuarios to set
	 */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the nacionalidad
	 */
	public Nacionalidad getNacionalidad() {
		return nacionalidad;
	}

	/**
	 * @param nacionalidad the nacionalidad to set
	 */
	public void setNacionalidad(Nacionalidad nacionalidad) {
		this.nacionalidad = nacionalidad;
	}


}
