package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private Date fechaInicio;
	private Date fechaFin;
//	private String estadoRegistro;
	private Date fechaInsercion;
	private String usuarioInsercion;
	private String ipInsercion;
	private Date fechaModificacion;
	private String usuarioModificacion;
	private String ipModificacion;

	public Calendario() {
	}

	public Calendario(String denominacion, Date fechaInicio, Date fechaFin,
			String estadoRegistro) {
		this.denominacion = denominacion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
//		this.estadoRegistro = estadoRegistro;
	}

	public Calendario(String denominacion, Date fechaInicio, Date fechaFin,
			String estadoRegistro, Date fechaInsercion, String usuarioInsercion,
			String ipInsercion, Date fechaModificacion,
			String usuarioModificacion, String ipModificacion) {
		this.denominacion = denominacion;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
//		this.estadoRegistro = estadoRegistro;
		this.fechaInsercion = fechaInsercion;
		this.usuarioInsercion = usuarioInsercion;
		this.ipInsercion = ipInsercion;
		this.fechaModificacion = fechaModificacion;
		this.usuarioModificacion = usuarioModificacion;
		this.ipModificacion = ipModificacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

//	public String getEstadoRegistro() {
//		return this.estadoRegistro;
//	}
//
//	public void setEstadoRegistro(String estadoRegistro) {
//		this.estadoRegistro = estadoRegistro;
//	}

	@Override
	public Date getFechaInsercion() {
		return this.fechaInsercion;
	}

	@Override
	public void setFechaInsercion(Date fechaInsercion) {
		this.fechaInsercion = fechaInsercion;
	}

	@Override
	public String getUsuarioInsercion() {
		return this.usuarioInsercion;
	}

	@Override
	public void setUsuarioInsercion(String usuarioInsercion) {
		this.usuarioInsercion = usuarioInsercion;
	}

	@Override
	public String getIpInsercion() {
		return this.ipInsercion;
	}

	@Override
	public void setIpInsercion(String ipInsercion) {
		this.ipInsercion = ipInsercion;
	}

	@Override
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	@Override
	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Override
	public String getUsuarioModificacion() {
		return this.usuarioModificacion;
	}

	@Override
	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Override
	public String getIpModificacion() {
		return this.ipModificacion;
	}

	@Override
	public void setIpModificacion(String ipModificacion) {
		this.ipModificacion = ipModificacion;
	}

}
