package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * ControlEspecieValoradaId generated by hbm2java
 */
public class ControlEspecieValoradaID implements java.io.Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Integer idTipoComprobante;
	private Integer idUsuarioHardware;
	private Integer idEmpresa;
	private String strSerie;

	public ControlEspecieValoradaID() {
	}
	/**
	 * @param idTipoComprobante
	 * @param idUsuarioHardware
	 */
	public ControlEspecieValoradaID(Integer idTipoComprobante, Integer idUsuarioHardware, String strSerie) {
		super();
		this.idTipoComprobante = idTipoComprobante;
		this.idUsuarioHardware = idUsuarioHardware;
		this.strSerie = strSerie;
	}
	/**
	 * @return Objeto idTipoComprobante.
	 */
	public Integer getIdTipoComprobante() {
		return idTipoComprobante;
	}
	/**
	 * @param idTipoComprobante	: Setea el objeto idTipoComprobante.
	 */
	public void setIdTipoComprobante(Integer idTipoComprobante) {
		this.idTipoComprobante = idTipoComprobante;
	}

	/**
	 * @return Objeto idUsuarioHardware.
	 */
	public Integer getIdUsuarioHardware() {
		return idUsuarioHardware;
	}
	/**
	 * @param idUsuarioHardware	: Setea el objeto idUsuarioHardware.
	 */
	public void setIdUsuarioHardware(Integer idUsuarioHardware) {
		this.idUsuarioHardware = idUsuarioHardware;
	}
	/**
	 * @return the strSerie
	 */
	public String getStrSerie() {
		return strSerie;
	}
	/**
	 * @param strSerie the strSerie to set
	 */
	public void setStrSerie(String strSerie) {
		this.strSerie = strSerie;
	}
	/**
	 * @return the idEmpresa
	 */
	public Integer getIdEmpresa() {
		return idEmpresa;
	}
	/**
	 * @param idEmpresa the idEmpresa to set
	 */
	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}


//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof ControlEspecieValoradaID))
//			return false;
//		ControlEspecieValoradaID castOther = (ControlEspecieValoradaID) other;
//
//		return (this.getIdTipoComprobante() == castOther.getIdTipoComprobante())
//				&& (this.getIdUsuarioHardware() == castOther.getIdUsuarioHardware())
//				&& (this.getSerie() == castOther.getSerie());
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (Integer) this.getIdTipoComprobante();
//		result = 37 * result + this.getIdUsuarioHardware();
////		result = 37 * result + this.getSerie());
//		return result;
//	}

}
