package pe.itsb.vyrbus.model.bean;

import java.io.Serializable;

import pe.itsb.vyrbus.service.util.Util;

// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1


/**
 * ControlEspecieValorada generated by hbm2java
 */
public class ControlEspecieValorada extends GenericBean implements Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private ControlEspecieValoradaID controlEspecieValoradaID;
	private UsuarioHardware usuarioHardware;
	private TipoComprobante tipoComprobante;
	private Empresa empresa;
	private String serie;
	private Long correlativoInicio;
	private Long correlativoFin;
	private Long correlativoActual;
	private Integer formato;
	private Agencia agencia;
	private String secuenciador;
	private Integer aplica;

	public ControlEspecieValorada() {
	}

	/**
	 * @return Objeto controlEspecieValoradaID.
	 */

	public ControlEspecieValoradaID getControlEspecieValoradaID() {
		return controlEspecieValoradaID;
	}
	/*
	 * @param controlEspecieValoradaID	: Setea el objeto controlEspecieValoradaID.
	 */

	public void setControlEspecieValoradaID(ControlEspecieValoradaID controlEspecieValoradaID) {
		this.controlEspecieValoradaID = controlEspecieValoradaID;
	}

	public UsuarioHardware getUsuarioHardware() {
		return this.usuarioHardware;
	}
	public void setUsuarioHardware(UsuarioHardware usuarioHardware) {
		this.usuarioHardware = usuarioHardware;
	}

	public TipoComprobante getTipoComprobante() {
		return this.tipoComprobante;
	}
	public void setTipoComprobante(TipoComprobante tipoComprobante) {
		this.tipoComprobante = tipoComprobante;
	}

	/**
	 * @return the empresa
	 */
	public Empresa getEmpresa() {
		return empresa;
	}

	/**
	 * @param empresa the empresa to set
	 */
	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	public String getSerie() {
		return this.serie;
	}
	public void setSerie(String serie) {
		this.serie = serie;
	}

	public Long getCorrelativoInicio() {
		return this.correlativoInicio;
	}
	public void setCorrelativoInicio(Long correlativoInicio) {
		this.correlativoInicio = correlativoInicio;
	}

	public Long getCorrelativoFin() {
		return this.correlativoFin;
	}
	public void setCorrelativoFin(Long correlativoFin) {
		this.correlativoFin = correlativoFin;
	}

	public Long getCorrelativoActual() {
		return this.correlativoActual;
	}
	public void setCorrelativoActual(Long correlativoActual) {
		this.correlativoActual = correlativoActual;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
////		Long actual = correlativoActual+1;
//		Long actual = correlativoActual;
//		String correlativo = "0000000"+actual;
//		return this.serie + "-"+ correlativo.substring(correlativo.length()-7);
		Long actual = correlativoActual;
		/*para el caso de la fe*/
//		String correlativo = "00000000"+actual;
		String correlativo = actual.toString();
		String cserie=this.serie;
//		return cserie + "-"+ correlativo.substring(correlativo.length()-8);
		return Util.autocompleNumberBoleto(cserie+"-"+correlativo);
	}

	/**
	 * @return the formato
	 */
	public Integer getFormato() {
		return formato;
	}

	/**
	 * @param formato the formato to set
	 */
	public void setFormato(Integer formato) {
		this.formato = formato;
	}

	/**
	 * @return the agencia
	 */
	public Agencia getAgencia() {
		return agencia;
	}

	/**
	 * @param agencia the agencia to set
	 */
	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	/**
	 * @return the secuenciador
	 */
	public String getSecuenciador() {
		return secuenciador;
	}

	/**
	 * @param secuenciador the secuenciador to set
	 */
	public void setSecuenciador(String secuenciador) {
		this.secuenciador = secuenciador;
	}

	/**
	 * @return the aplica
	 */
	public Integer getAplica() {
		return aplica;
	}

	/**
	 * @param aplica the aplica to set
	 */
	public void setAplica(Integer aplica) {
		this.aplica = aplica;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}
}
