package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DescuentoRecargo generated by hbm2java
 */
public class DescuentoRecargo extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;
	private Double monto;
	private Integer esPorcentaje;

	private Set<DetallePago> detallePagos = new HashSet<>(0);

	public DescuentoRecargo() {
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Double getMonto() {
		return this.monto;
	}
	public void setMonto(Double monto) {
		this.monto = monto;
	}

	public Integer isEsPorcentaje() {
		return this.esPorcentaje;
	}
	public void setEsPorcentaje(Integer esPorcentaje) {
		this.esPorcentaje = esPorcentaje;
	}

	public Set<DetallePago> getDetallePagos() {
		return this.detallePagos;
	}
	public void setDetallePagos(Set<DetallePago> detallePagos) {
		this.detallePagos = detallePagos;
	}

}
