package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import pe.itsb.vyrbus.service.mappers.SecuenciaTramo;

/**
 * Itinerario generated by hbm2java
 */
public class Itinerario extends GenericBean implements Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private TipoItinerario tipoItinerario;
	private Bus bus;
	private Ruta ruta;
	private Servicio servicio;
	private Agencia agenciaPartida;
	private Agencia agenciaLlegada;
	private Empresa empresa;
	private Date fechaPartida;
	private String horaPartida;
	private Date fechaLlegada;
	private String horaLlegada;
	private Integer esAnulado;
	private String secuenciaTramo;
	private Date fechaRealPartida;

	private List<SecuenciaTramo> listSecuenciaTramo;		//No mapeado
	private String operadoPor; //No Mapeado

	public Itinerario() {
	}

	/**
	 * @param id
	 */
	public Itinerario(Long id) {
		super();
		this.id = id;
	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return Objeto tipoItinerario.
	 */
	public TipoItinerario getTipoItinerario() {
		return tipoItinerario;
	}
	/**
	 * @param tipoItinerario	: Setea el objeto tipoItinerario.
	 */
	public void setTipoItinerario(TipoItinerario tipoItinerario) {
		this.tipoItinerario = tipoItinerario;
	}

	/**
	 * @return Objeto bus.
	 */
	public Bus getBus() {
		return bus;
	}
	/**
	 * @param bus	: Setea el objeto bus.
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * @return Objeto ruta.
	 */
	public Ruta getRuta() {
		return ruta;
	}
	/**
	 * @param ruta	: Setea el objeto ruta.
	 */
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	/**
	 * @return Objeto servicio.
	 */
	public Servicio getServicio() {
		return servicio;
	}
	/**
	 * @param servicio	: Setea el objeto servicio.
	 */
	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return Objeto agenciaPartida.
	 */
	public Agencia getAgenciaPartida() {
		return agenciaPartida;
	}
	/**
	 * @param agenciaPartida	: Setea el objeto agenciaPartida.
	 */
	public void setAgenciaPartida(Agencia agenciaPartida) {
		this.agenciaPartida = agenciaPartida;
	}

	/**
	 * @return Objeto agenciaLlegada.
	 */
	public Agencia getAgenciaLlegada() {
		return agenciaLlegada;
	}
	/**
	 * @param agenciaLlegada	: Setea el objeto agenciaLlegada.
	 */
	public void setAgenciaLlegada(Agencia agenciaLlegada) {
		this.agenciaLlegada = agenciaLlegada;
	}

	/**
	 * @return the empresa
	 */
	public Empresa getEmpresa() {
		return empresa;
	}

	/**
	 * @param empresa the empresa to set
	 */
	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	/**
	 * @return Objeto fechaPartida.
	 */
	public Date getFechaPartida() {
		return fechaPartida;
	}
	/**
	 * @param fechaPartida	: Setea el objeto fechaPartida.
	 */
	public void setFechaPartida(Date fechaPartida) {
		this.fechaPartida = fechaPartida;
	}

	/**
	 * @return Objeto horaPartida.
	 */
	public String getHoraPartida() {
		return horaPartida;
	}
	/**
	 * @param horaPartida	: Setea el objeto horaPartida.
	 */
	public void setHoraPartida(String horaPartida) {
		this.horaPartida = horaPartida;
	}

	/**
	 * @return Objeto fechaLlegada.
	 */
	public Date getFechaLlegada() {
		return fechaLlegada;
	}
	/**
	 * @param fechaLlegada	: Setea el objeto fechaLlegada.
	 */
	public void setFechaLlegada(Date fechaLlegada) {
		this.fechaLlegada = fechaLlegada;
	}

	/**
	 * @return Objeto horaLlegada.
	 */
	public String getHoraLlegada() {
		return horaLlegada;
	}
	/**
	 * @param horaLlegada	: Setea el objeto horaLlegada.
	 */
	public void setHoraLlegada(String horaLlegada) {
		this.horaLlegada = horaLlegada;
	}

	/**
	 * @return Objeto esAnulado.
	 */
	public Integer getEsAnulado() {
		return esAnulado;
	}
	/**
	 * @param esAnulado	: Setea el objeto esAnulado.
	 */
	public void setEsAnulado(Integer esAnulado) {
		this.esAnulado = esAnulado;
	}

	/**
	 * @return Objeto secuenciaTramo.
	 */
	public String getSecuenciaTramo() {
		return secuenciaTramo;
	}
	/**
	 * @param secuenciaTramo	: Setea el objeto secuenciaTramo.
	 */
	public void setSecuenciaTramo(String secuenciaTramo) {
		this.secuenciaTramo = secuenciaTramo;
		setListSecuenciaTramo(obtenerSecuencia(secuenciaTramo));
	}

	/**
	 * @return Objeto listSecuenciaTramo.
	 */
	public List<SecuenciaTramo> getListSecuenciaTramo() {
		return listSecuenciaTramo;
	}
	/**
	 * @param listSecuenciaTramo	: Setea el objeto listSecuenciaTramo.
	 */
	public void setListSecuenciaTramo(List<SecuenciaTramo> listSecuenciaTramo) {
		this.listSecuenciaTramo = listSecuenciaTramo;
	}

	/**
	 * @return the fechaRealPartida
	 */
	public Date getFechaRealPartida() {
		return fechaRealPartida;
	}
	/**
	 * @param fechaRealPartida the fechaRealPartida to set
	 */
	public void setFechaRealPartida(Date fechaRealPartida) {
		this.fechaRealPartida = fechaRealPartida;
	}

	private List<SecuenciaTramo> obtenerSecuencia(String secuencia){
		String[] sArray = secuencia.split(";");
		List<SecuenciaTramo> lstResult = new ArrayList<>();
		for(String obj : sArray){
			SecuenciaTramo secuenciaTramo = new SecuenciaTramo();
			String[] buffer = obj.split("-");
			secuenciaTramo.setOrigen(Integer.valueOf(buffer[0]));
			secuenciaTramo.setDestino(Integer.valueOf(buffer[1]));
			secuenciaTramo.setOrden(Integer.valueOf(buffer[2]));
			lstResult.add(secuenciaTramo);
		}
		return lstResult;
	}

	/**
	 * @return the operadoPor
	 */
	public String getOperadoPor() {
		return operadoPor;
	}

	/**
	 * @param operadoPor the operadoPor to set
	 */
	public void setOperadoPor(String operadoPor) {
		this.operadoPor = operadoPor;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
