package pe.itsb.vyrbus.model.bean;

// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * Vrmopcmen generated by hbm2java
 */
public class OpcionMenu extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private OpcionMenu opcionMenuPadre;
	private String denominacion;
	private String nombreObjeto;
	private String url;
	private Integer ordenOpcionMenu;
	private Integer habilitado;

	private Integer idPadre;
	private String padre;
	private Integer idHijo;
	private String hijo;

	public OpcionMenu() {
	}

	/**
	 * @return Objeto id.
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return Objeto opcionMenuPadre.
	 */
	public OpcionMenu getOpcionMenuPadre() {
		return opcionMenuPadre;
	}

	/**
	 * @param opcionMenuPadre	: Setea el objeto opcionMenuPadre.
	 */
	public void setOpcionMenuPadre(OpcionMenu opcionMenuPadre) {
		this.opcionMenuPadre = opcionMenuPadre;
	}

	/**
	 * @return Objeto denominacion.
	 */
	public String getDenominacion() {
		return denominacion;
	}

	/**
	 * @param denominacion	: Setea el objeto denominacion.
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	/**
	 * @return Objeto nombreObjeto.
	 */
	public String getNombreObjeto() {
		return nombreObjeto;
	}

	/**
	 * @param nombreObjeto	: Setea el objeto nombreObjeto.
	 */
	public void setNombreObjeto(String nombreObjeto) {
		this.nombreObjeto = nombreObjeto;
	}

	/**
	 * @return Objeto url.
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url	: Setea el objeto url.
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return Objeto ordenOpcionMenu.
	 */
	public Integer getOrdenOpcionMenu() {
		return ordenOpcionMenu;
	}

	/**
	 * @param ordenOpcionMenu	: Setea el objeto ordenOpcionMenu.
	 */
	public void setOrdenOpcionMenu(Integer ordenOpcionMenu) {
		this.ordenOpcionMenu = ordenOpcionMenu;
	}

	/**
	 * @return Objeto habilitado.
	 */
	public Integer getHabilitado() {
		return habilitado;
	}

	/**
	 * @param habilitado	: Setea el objeto habilitado.
	 */
	public void setHabilitado(Integer habilitado) {
		this.habilitado = habilitado;
	}

	/**
	 * @return the idPadre
	 */
	public Integer getIdPadre() {
		return idPadre;
	}
	/**
	 * @param idPadre the idPadre to set
	 */
	public void setIdPadre(Integer idPadre) {
		this.idPadre = idPadre;
	}

	/**
	 * @return the padre
	 */
	public String getPadre() {
		return padre;
	}
	/**
	 * @param padre the padre to set
	 */
	public void setPadre(String padre) {
		this.padre = padre;
	}

	/**
	 * @return the idHijo
	 */
	public Integer getIdHijo() {
		return idHijo;
	}
	/**
	 * @param idHijo the idHijo to set
	 */
	public void setIdHijo(Integer idHijo) {
		this.idHijo = idHijo;
	}

	/**
	 * @return the hijo
	 */
	public String getHijo() {
		return hijo;
	}
	/**
	 * @param hijo the hijo to set
	 */
	public void setHijo(String hijo) {
		this.hijo = hijo;
	}
}
