package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * OperadorTarjetaCredito generated by hbm2java
 */
public class OperadorTarjetaCredito extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominacion;

	private Set<TarjetaCredito> tarjetaCreditos = new HashSet<>(0);

	public OperadorTarjetaCredito() {
		super();
	}

	public OperadorTarjetaCredito(Integer id){
		this.id=id;
	}

	public Integer getId() {
		return this.id;
	}
	public void setId(Integer id) {
		this.id = id;
	}

	public String getDenominacion() {
		return this.denominacion;
	}
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public Set<TarjetaCredito> getTarjetaCreditos() {
		return this.tarjetaCreditos;
	}
	public void setTarjetaCreditos(Set<TarjetaCredito> tarjetaCreditos) {
		this.tarjetaCreditos = tarjetaCreditos;
	}

}
