package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProgramacionServicio generated by hbm2java
 */
public class ProgramacionServicio extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Itinerario itinerario;
	private Bus bus;
	private Personal piloto;
	private Personal copiloto;
	private Personal tripulante;
	private Personal copilotoAuxiliar;

	private HRE hojaRuta; //No mapeado
	private Boolean MEE; //No mapeado (determina si el manifiesto electronico ya fue emitido)
//	private MTCDetalleRuta mtcDetalleRuta; //No mapeado. (Utilizado en la impresion de la HRE)
//	private MTCDireccionTerminal mtcDireccionTerminalPart; //No mapeado. (Utilizado en la impresion de la HRE)
//	private MTCDireccionTerminal mtcDireccionTerminalLleg; //No mapeado. (Utilizado en la impresion de la HRE)


	public ProgramacionServicio() {

	}

	/**
	 * @return Objeto id.
	 */
	public Long getId() {
		return id;
	}
	/**
	 * @param id	: Setea el objeto id.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return Objeto itinerario.
	 */
	public Itinerario getItinerario() {
		return itinerario;
	}
	/**
	 * @param itinerario	: Setea el objeto itinerario.
	 */
	public void setItinerario(Itinerario itinerario) {
		this.itinerario = itinerario;
	}

	/**
	 * @return Objeto bus.
	 */
	public Bus getBus() {
		return bus;
	}
	/**
	 * @param bus	: Setea el objeto bus.
	 */
	public void setBus(Bus bus) {
		this.bus = bus;
	}

	/**
	 * @return Objeto piloto.
	 */
	public Personal getPiloto() {
		return piloto;
	}
	/**
	 * @param piloto	: Setea el objeto piloto.
	 */
	public void setPiloto(Personal piloto) {
		this.piloto = piloto;
	}

	/**
	 * @return Objeto copiloto.
	 */
	public Personal getCopiloto() {
		return copiloto;
	}
	/**
	 * @param copiloto	: Setea el objeto copiloto.
	 */
	public void setCopiloto(Personal copiloto) {
		this.copiloto = copiloto;
	}

	/**
	 * @return Objeto tripulante.
	 */
	public Personal getTripulante() {
		return tripulante;
	}
	/**
	 * @param tripulante	: Setea el objeto tripulante.
	 */
	public void setTripulante(Personal tripulante) {
		this.tripulante = tripulante;
	}

	/**
	 * @return the copilotoAuxiliar
	 */
	public Personal getCopilotoAuxiliar() {
		return copilotoAuxiliar;
	}

	/**
	 * @param copilotoAuxiliar the copilotoAuxiliar to set
	 */
	public void setCopilotoAuxiliar(Personal copilotoAuxiliar) {
		this.copilotoAuxiliar = copilotoAuxiliar;
	}

	/**
	 * @return the hojaRuta
	 */
	public HRE getHojaRuta() {
		return hojaRuta;
	}

	/**
	 * @param hojaRuta the hojaRuta to set
	 */
	public void setHojaRuta(HRE hojaRuta) {
		this.hojaRuta = hojaRuta;
	}

	/**
	 * @return the mEE
	 */
	public Boolean isMEE() {
		return MEE;
	}

	/**
	 * @param mEE the mEE to set
	 */
	public void setMEE(Boolean mEE) {
		MEE = mEE;
	}

//	/**
//	 * @return the mtcDetalleRuta
//	 */
//	public MTCDetalleRuta getMtcDetalleRuta() {
//		return mtcDetalleRuta;
//	}
//
//	/**
//	 * @param mtcDetalleRuta the mtcDetalleRuta to set
//	 */
//	public void setMtcDetalleRuta(MTCDetalleRuta mtcDetalleRuta) {
//		this.mtcDetalleRuta = mtcDetalleRuta;
//	}

//	/**
//	 * @return the mtcDireccionTerminalPart
//	 */
//	public MTCDireccionTerminal getMtcDireccionTerminalPart() {
//		return mtcDireccionTerminalPart;
//	}
//
//	/**
//	 * @param mtcDireccionTerminalPart the mtcDireccionTerminalPart to set
//	 */
//	public void setMtcDireccionTerminalPart(MTCDireccionTerminal mtcDireccionTerminalPart) {
//		this.mtcDireccionTerminalPart = mtcDireccionTerminalPart;
//	}
//
//	/**
//	 * @return the mtcDireccionTerminalLleg
//	 */
//	public MTCDireccionTerminal getMtcDireccionTerminalLleg() {
//		return mtcDireccionTerminalLleg;
//	}
//
//	/**
//	 * @param mtcDireccionTerminalLleg the mtcDireccionTerminalLleg to set
//	 */
//	public void setMtcDireccionTerminalLleg(MTCDireccionTerminal mtcDireccionTerminalLleg) {
//		this.mtcDireccionTerminalLleg = mtcDireccionTerminalLleg;
//	}


}
