package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

//import java.util.Date;

/**
 * Tarifa generated by hbm2java
 */
public class Tarifa extends GenericBean implements java.io.Serializable, Cloneable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private CanalVenta canalVenta;
	private Servicio servicio;
	private Ruta ruta;
	private Integer pisoBus;
	private Integer zonaBus;
	private Empresa empresa;

	public Tarifa() {
	}

	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}

	public Ruta getRuta() {
		return this.ruta;
	}
	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	public CanalVenta getCanalVenta() {
		return canalVenta;
	}

	public void setCanalVenta(CanalVenta canalVenta) {
		this.canalVenta = canalVenta;
	}

	public Servicio getServicio() {
		return servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	public Integer getPisoBus() {
		return pisoBus;
	}

	public void setPisoBus(Integer pisoBus) {
		this.pisoBus = pisoBus;
	}

	public Integer getZonaBus() {
		return zonaBus;
	}

	public void setZonaBus(Integer zonaBus) {
		this.zonaBus = zonaBus;
	}

	/**
	 * @return the empresa
	 */
	public Empresa getEmpresa() {
		return empresa;
	}

	/**
	 * @param empresa the empresa to set
	 */
	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

}
