package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * TarjetaCredito generated by hbm2java
 */
public class TarjetaCredito extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private OperadorTarjetaCredito operadorTarjetaCredito;
	private String denominacion;

	public TarjetaCredito() {
		super();
	}

	public TarjetaCredito(Integer id){
		this.id=id;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the operadorTarjetaCredito
	 */
	public OperadorTarjetaCredito getOperadorTarjetaCredito() {
		return operadorTarjetaCredito;
	}
	/**
	 * @param operadorTarjetaCredito the operadorTarjetaCredito to set
	 */
	public void setOperadorTarjetaCredito(OperadorTarjetaCredito operadorTarjetaCredito) {
		this.operadorTarjetaCredito = operadorTarjetaCredito;
	}

	/**
	 * @return the denominacion
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion the denominacion to set
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return this.denominacion;
	}
}
