package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * TipoFormaPago generated by hbm2java
 */
public class TipoFormaPago extends GenericBean implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private FormaPago formaPago;
	private String denominacion;
	private String nombreCorto;
	private Integer tipoIngresoLiquidacion;
	private Integer esPromocion;

	public static final String TIPO_TARJETA = "TARJETA";
	public static final String TIPO_TRANSFERENCIA = "TRANSFERENCIA";
	public static final String TIPO_CREDITO = "CREDITO";
	public static final Integer N_ESPROMOCION = 1;

	public TipoFormaPago() {
		super();
	}

	public TipoFormaPago(Integer id){
		this.id=id;
	}

	public TipoFormaPago(Integer id, String denuminacion){
		this.id=id;
		this.denominacion = denuminacion;
	}

	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the formaPago
	 */
	public FormaPago getFormaPago() {
		return formaPago;
	}
	/**
	 * @param formaPago the formaPago to set
	 */
	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}

	/**
	 * @return the denominacion
	 */
	public String getDenominacion() {
		return denominacion;
	}
	/**
	 * @param denominacion the denominacion to set
	 */
	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	/**
	 * @return the nombreCorto
	 */
	public String getNombreCorto() {
		return nombreCorto;
	}
	/**
	 * @param nombreCorto the nombreCorto to set
	 */
	public void setNombreCorto(String nombreCorto) {
		this.nombreCorto = nombreCorto;
	}

	/**
	 * @return the tipoIngresoLiquidacion
	 */
	public Integer getTipoIngresoLiquidacion() {
		return tipoIngresoLiquidacion;
	}
	/**
	 * @param tipoIngresoLiquidacion the tipoIngresoLiquidacion to set
	 */
	public void setTipoIngresoLiquidacion(Integer tipoIngresoLiquidacion) {
		this.tipoIngresoLiquidacion = tipoIngresoLiquidacion;
	}

	/**
	 * @return the esPromocion
	 */
	public Integer getEsPromocion() {
		return esPromocion;
	}
	/**
	 * @param esPromocion the esPromocion to set
	 */
	public void setEsPromocion(Integer esPromocion) {
		this.esPromocion = esPromocion;
	}
}
