package pe.itsb.vyrbus.model.bean;
// default package
// Generated 24/05/2012 11:51:01 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioRolId generated by hbm2java
 */
public class UsuarioRolID extends GenericBean implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 1L;


	private Integer idUsuario;
	private Integer idRol;

	public UsuarioRolID() {
	}

	public UsuarioRolID(Integer idRol, Integer idUsuario) {
		super();
		this.idRol = idRol;
		this.idUsuario = idUsuario;
	}

	/**
	 * @return Objeto idUsuario.
	 */
	public Integer getIdUsuario() {
		return idUsuario;
	}
	/**
	 * @param idUsuario	: Setea el objeto idUsuario.
	 */
	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	/**
	 * @return Objeto idRol.
	 */
	public int getIdRol() {
		return idRol;
	}
	/**
	 * @param idRol	: Setea el objeto idRol.
	 */
	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null) || !(other instanceof UsuarioRolID))
			return false;
		UsuarioRolID castOther = (UsuarioRolID) other;

		return (this.getIdRol() == castOther.getIdRol())
				&& (this.getIdUsuario() == castOther.getIdUsuario());
	}
}
