package com.cystesoft.vyrbus.service.fe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IMEFEService", targetNamespace = "http://tempuri.org/")
public interface IMEFEService {

	/**
	 * 
	 * @param token
	 * @param venta
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setVenta")
	@WebResult(name = "setVentaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setVenta", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetVenta")
	@ResponseWrapper(localName = "setVentaResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetVentaResponse")
	public Result setVenta(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "venta", targetNamespace = "http://tempuri.org/") Venta venta);

	/**
	 * 
	 * @param notaCreditoDebito
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setNota")
	@WebResult(name = "setNotaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setNota", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetNota")
	@ResponseWrapper(localName = "setNotaResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetNotaResponse")
	public Result setNota(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "notaCreditoDebito", targetNamespace = "http://tempuri.org/") Nota notaCreditoDebito);

	/**
	 * 
	 * @param rucEmpresa
	 * @param fechaEmisionComprobantes
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setBajas")
	@WebResult(name = "setBajasResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setBajas", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetBajas")
	@ResponseWrapper(localName = "setBajasResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetBajasResponse")
	public Result setBajas(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "fechaEmisionComprobantes", targetNamespace = "http://tempuri.org/") String fechaEmisionComprobantes,
			@WebParam(name = "rucEmpresa", targetNamespace = "http://tempuri.org/") String rucEmpresa);

	/**
	 * 
	 * @param rucEmpresa
	 * @param fechaEmisionComprobantes
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setResumenes")
	@WebResult(name = "setResumenesResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setResumenes", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetResumenes")
	@ResponseWrapper(localName = "setResumenesResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetResumenesResponse")
	public Result setResumenes(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "fechaEmisionComprobantes", targetNamespace = "http://tempuri.org/") String fechaEmisionComprobantes,
			@WebParam(name = "rucEmpresa", targetNamespace = "http://tempuri.org/") String rucEmpresa);

	/**
	 * 
	 * @param rucEmpresa
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setUpdateStatusCDR")
	@WebResult(name = "setUpdateStatusCDRResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setUpdateStatusCDR", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetUpdateStatusCDR")
	@ResponseWrapper(localName = "setUpdateStatusCDRResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetUpdateStatusCDRResponse")
	public Result setUpdateStatusCDR(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "rucEmpresa", targetNamespace = "http://tempuri.org/") String rucEmpresa);

	/**
	 * 
	 * @param token
	 * @param documentoBaja
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setBajaDocumento")
	@WebResult(name = "setBajaDocumentoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setBajaDocumento", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetBajaDocumento")
	@ResponseWrapper(localName = "setBajaDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetBajaDocumentoResponse")
	public Result setBajaDocumento(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "documentoBaja", targetNamespace = "http://tempuri.org/") DocumentoBaja documentoBaja);

	/**
	 * 
	 * @param nota
	 * @param token
	 * @param venta
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setNotaVenta")
	@WebResult(name = "setNotaVentaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setNotaVenta", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetNotaVenta")
	@ResponseWrapper(localName = "setNotaVentaResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetNotaVentaResponse")
	public Result setNotaVenta(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "nota", targetNamespace = "http://tempuri.org/") Nota nota,
			@WebParam(name = "venta", targetNamespace = "http://tempuri.org/") Venta venta);

	/**
	 * 
	 * @param rucEmpresa
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setEnviarComprobantesSunat")
	@WebResult(name = "setEnviarComprobantesSunatResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setEnviarComprobantesSunat", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetEnviarComprobantesSunat")
	@ResponseWrapper(localName = "setEnviarComprobantesSunatResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetEnviarComprobantesSunatResponse")
	public Result setEnviarComprobantesSunat(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "rucEmpresa", targetNamespace = "http://tempuri.org/") String rucEmpresa);

	/**
	 * 
	 * @param serie
	 * @param isPasajes
	 * @param tipoComprobante
	 * @param token
	 * @param strRucEmpresa
	 * @param correlativo
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/getRepresentacionImpresa")
	@WebResult(name = "getRepresentacionImpresaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "getRepresentacionImpresa", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.GetRepresentacionImpresa")
	@ResponseWrapper(localName = "getRepresentacionImpresaResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.GetRepresentacionImpresaResponse")
	public Result getRepresentacionImpresa(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "isPasajes", targetNamespace = "http://tempuri.org/") Boolean isPasajes,
			@WebParam(name = "tipoComprobante", targetNamespace = "http://tempuri.org/") String tipoComprobante,
			@WebParam(name = "serie", targetNamespace = "http://tempuri.org/") String serie,
			@WebParam(name = "correlativo", targetNamespace = "http://tempuri.org/") String correlativo,
			@WebParam(name = "strRucEmpresa", targetNamespace = "http://tempuri.org/") String strRucEmpresa);

	/**
     * 
     */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setUpdatePdf")
	@RequestWrapper(localName = "setUpdatePdf", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetUpdatePdf")
	@ResponseWrapper(localName = "setUpdatePdfResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetUpdatePdfResponse")
	public void setUpdatePdf();

	/**
	 * 
	 * @param rucEmpresa
	 * @param serie
	 * @param tipoComprobante
	 * @param token
	 * @param correlativo
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/buscarDetalleComprobante")
	@WebResult(name = "buscarDetalleComprobanteResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "buscarDetalleComprobante", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.BuscarDetalleComprobante")
	@ResponseWrapper(localName = "buscarDetalleComprobanteResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.BuscarDetalleComprobanteResponse")
	public Result buscarDetalleComprobante(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "tipoComprobante", targetNamespace = "http://tempuri.org/") String tipoComprobante,
			@WebParam(name = "serie", targetNamespace = "http://tempuri.org/") String serie,
			@WebParam(name = "correlativo", targetNamespace = "http://tempuri.org/") String correlativo,
			@WebParam(name = "rucEmpresa", targetNamespace = "http://tempuri.org/") String rucEmpresa);

	/**
	 * 
	 * @param documentCDR
	 * @param token
	 * @return returns com.cystesoft.vyrbus.service.fe.Result
	 */
	@WebMethod(action = "http://tempuri.org/IMEFEService/setConsultarCDR")
	@WebResult(name = "setConsultarCDRResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "setConsultarCDR", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetConsultarCDR")
	@ResponseWrapper(localName = "setConsultarCDRResponse", targetNamespace = "http://tempuri.org/", className = "com.cystesoft.vyrbus.service.fe.SetConsultarCDRResponse")
	public Result setConsultarCDR(
			@WebParam(name = "token", targetNamespace = "http://tempuri.org/") String token,
			@WebParam(name = "documentCDR", targetNamespace = "http://tempuri.org/") DocumentCDR documentCDR);

}
