########################################################
####           PARAMETROS CONEXION PASAJES          ####
########################################################
jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.userName=vyrbustmr
jdbc.password=ENC(o18w908AjLV9zU0gsuFS76xZU12HZt+i)
########################################################
####                   DESARROLLO                   ####
########################################################
#jdbc.url=jdbc:oracle:thin:@192.168.0.34:1521:CDB1
#jdbc.url=jdbc:oracle:thin:@192.168.0.57:1521:DBTEST
########################################################
####              DEPURAR EN PRODUCCION             ####
########################################################
jdbc.url=jdbc:oracle:thin:@182.160.26.232:1521:TRANSMAR
########################################################
####                   PRODUCCION                   ####
########################################################
#jdbc.url=jdbc:oracle:thin:@192.168.1.101:1521:TRANSMAR
########################################################
####                 DEMO EN ANTEZANA               ####
########################################################
#jdbc.url=jdbc:oracle:thin:@192.168.50.10:1521:CDB1
########################################################

########################################################
####          PARAMETROS CONEXION CARGA WEB         ####
########################################################
jdbc.postgresql.driverClassName=org.postgresql.Driver
jdbc.transcarweb.username=transcar
jdbc.transcarweb.password=ventas5110
jdbc.transcarweb.url=jdbc:postgresql://182.160.26.232:5432/carga
########################################################
####                   PRODUCCION                   ####
########################################################
#jdbc.transcarweb.url=jdbc:postgresql://192.168.1.101:5432/carga
########################################################
####                 DEMO EN ANTEZANA               ####
########################################################
#jdbc.transcarweb.url=jdbc:postgresql://192.168.50.10:5432/carga
########################################################
#jdbc.transcar.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.transcar.userName=transcartmr
#jdbc.transcar.password=trnsmrcargo
jdbc.transcar.url=jdbc:oracle:thin:@192.168.50.10:1521:CDB1

########################################################
####	       PARAMETROS PARA HIBERNATE	        ####
########################################################
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.connection.autocommit=false
hibernate.jdbc.batch_size


########################################################
####	CREDENCIALES DE ACCESO PASAJES AMAZONAS     ####
########################################################
#jdbc.userName=vyrbusamz
#jdbc.password=ventas5110
