########################################################
####           PARAMETROS CONEXION PASAJES          ####
########################################################
jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.userName=vyrbustmr
jdbc.password=ENC(o18w908AjLV9zU0gsuFS76xZU12HZt+i)
########################################################
####             DESARROLLO - DEMO                  ####
########################################################
#jdbc.url=jdbc:oracle:thin:@170.0.233.156:1521:CDB1
#jdbc.url=jdbc:oracle:thin:@chachani.ddns.net:1521:CDB1
#jdbc.url=jdbc:oracle:thin:@10.0.2.17:1521:CDB1

#jdbc.url=jdbc:oracle:thin:@192.168.1.57:1521:DBTEST
########################################################
####              DEPURAR EN PRODUCCION             ####
########################################################
#jdbc.url=jdbc:oracle:thin:@182.160.26.232:1521:TRANSMAR
########################################################
####                   PRODUCCION                   ####
########################################################
jdbc.url=jdbc:oracle:thin:@192.168.1.101:1521:TRANSMAR
########################################################

########################################################
####          PARAMETROS CONEXION CARGA WEB         ####
########################################################
jdbc.postgresql.driverClassName=org.postgresql.Driver
jdbc.transcarweb.username=transcar
jdbc.transcarweb.password=ventas5110

########################################################
####                   PRODUCCION                   ####
########################################################
jdbc.transcarweb.url=jdbc:postgresql://192.168.1.101:5432/carga
########################################################
####              DEPURAR EN PRODUCCION             ####
########################################################
#jdbc.transcarweb.url=jdbc:postgresql://182.160.26.232:5432/carga
#DEMO
#jdbc.transcarweb.url=jdbc:postgresql://10.0.2.17:5432/democarga
#jdbc.transcarweb.url=jdbc:postgresql://chachani.ddns.net:5432/carga


#jdbc.transcar.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.transcar.userName=transcartmr
#jdbc.transcar.password=trnsmrcargo
jdbc.transcar.url=jdbc:oracle:thin:@192.168.50.10:1521:CDB1

########################################################
####	       PARAMETROS PARA HIBERNATE	        ####
########################################################
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.connection.autocommit=false
hibernate.jdbc.batch_size

########################################################
####	CREDENCIALES DE ACCESO PASAJES AMAZONAS     ####
########################################################
#jdbc.userName=vyrbusamz
#jdbc.password=ventas5110