
package pe.itsb.vyrbus.service.fe;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
* MEFEService service = new MEFEService();
* IMEFEService portType = service.getBasicHttpBindingIMEFEService();
* portType.setVenta(...);
 * </pre>
 * </p>
 *
 */
@WebServiceClient(name = "MEFEService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.0.211:8085/MEFEService.svc?wsdl")
public class MEFEService extends Service {

	private final static URL MEFESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(pe.itsb.vyrbus.service.fe.MEFEService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = pe.itsb.vyrbus.service.fe.MEFEService.class.getResource(".");

			url = new URL(baseUrl, "http://192.168.0.211:8085/MEFEService.svc?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://192.168.0.211_119.8.148.239:8085/MEFEService.svc?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MEFESERVICE_WSDL_LOCATION = url;
	}

	public MEFEService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MEFEService() {
		super(MEFESERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "MEFEService"));
	}

	/**
	 *
	 * @return returns IMEFEService
	 */
	@WebEndpoint(name = "BasicHttpBinding_IMEFEService")
	public IMEFEService getBasicHttpBindingIMEFEService() {
		return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IMEFEService"), IMEFEService.class);
	}

}
