package cruzdelsur.ws.com.pe;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Servicecruzdelsur service = new Servicecruzdelsur();
 * IServicecruzdelsur portType = service.getBasicHttpBindingIServicecruzdelsur();
 * portType.obtenerHorarios(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Servicecruzdelsur", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.200.80:8080/Servicecruzdelsur.svc?wsdl")
public class Servicecruzdelsur extends Service {

	private final static URL SERVICECRUZDELSUR_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(cruzdelsur.ws.com.pe.Servicecruzdelsur.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = cruzdelsur.ws.com.pe.Servicecruzdelsur.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://192.168.200.80:8080/Servicecruzdelsur.svc?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.200.80:8080/Servicecruzdelsur.svc?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICECRUZDELSUR_WSDL_LOCATION = url;
	}

	public Servicecruzdelsur(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Servicecruzdelsur() {
		super(SERVICECRUZDELSUR_WSDL_LOCATION, new QName("http://tempuri.org/",
				"Servicecruzdelsur"));
	}

	/**
	 * 
	 * @return returns IServicecruzdelsur
	 */
	@WebEndpoint(name = "BasicHttpBinding_IServicecruzdelsur")
	public IServicecruzdelsur getBasicHttpBindingIServicecruzdelsur() {
		return super.getPort(new QName("http://tempuri.org/",
				"BasicHttpBinding_IServicecruzdelsur"),
				IServicecruzdelsur.class);
	}

}
