package pe.gob.mtc.wshr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "WSServiciosHRSoap", targetNamespace = "http://wshr.mtc.gob.pe/")
public interface WSServiciosHRSoap {

	/**
	 * Informacion de Conductor por Empresa de Transporte.
	 *
	 * @param oConductor
	 * @return returns pe.gob.mtc.wshr.ResultConductor
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getConductor")
	@WebResult(name = "getConductorResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getConductor", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetConductor")
	@ResponseWrapper(localName = "getConductorResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetConductorResponse")
	public ResultConductor getConductor(
			@WebParam(name = "oConductor", targetNamespace = "http://wshr.mtc.gob.pe/") Conductor oConductor);

	/**
	 * Informacion de Pasajero por Empresa de Transporte.
	 *
	 * @param oIdentidad
	 * @return returns pe.gob.mtc.wshr.ResultIdentidad
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getIdentidad")
	@WebResult(name = "getIdentidadResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getIdentidad", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetIdentidad")
	@ResponseWrapper(localName = "getIdentidadResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetIdentidadResponse")
	public ResultIdentidad getIdentidad(
			@WebParam(name = "oIdentidad", targetNamespace = "http://wshr.mtc.gob.pe/") Identidad oIdentidad);

	/**
	 * Informacion de Parametro por Empresa de Transporte.
	 *
	 * @param oParametro
	 * @return returns pe.gob.mtc.wshr.ResultParametro
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getParametro")
	@WebResult(name = "getParametroResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getParametro", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetParametro")
	@ResponseWrapper(localName = "getParametroResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetParametroResponse")
	public ResultParametro getParametro(
			@WebParam(name = "oParametro", targetNamespace = "http://wshr.mtc.gob.pe/") Parametro oParametro);

	/**
	 * Informacion de Vehiculo por Empresa de Transporte.
	 *
	 * @param oVehiculo
	 * @return returns pe.gob.mtc.wshr.ResultVehiculo
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getVehiculo")
	@WebResult(name = "getVehiculoResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getVehiculo", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetVehiculo")
	@ResponseWrapper(localName = "getVehiculoResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetVehiculoResponse")
	public ResultVehiculo getVehiculo(
			@WebParam(name = "oVehiculo", targetNamespace = "http://wshr.mtc.gob.pe/") Vehiculo oVehiculo);

	/**
	 * Anulacion de Hoja Ruta por Empresa de Transporte.
	 *
	 * @param oAnular
	 * @return returns pe.gob.mtc.wshr.ResultAnular
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setAnular")
	@WebResult(name = "setAnularResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setAnular", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetAnular")
	@ResponseWrapper(localName = "setAnularResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetAnularResponse")
	public ResultAnular setAnular(
			@WebParam(name = "oAnular", targetNamespace = "http://wshr.mtc.gob.pe/") Anular oAnular);

	/**
	 * Finalizacion de Hoja Ruta por Empresa de Transporte.
	 *
	 * @param oFinalizar
	 * @return returns pe.gob.mtc.wshr.ResultFinalizar
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setFinalizar")
	@WebResult(name = "setFinalizarResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setFinalizar", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetFinalizar")
	@ResponseWrapper(localName = "setFinalizarResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetFinalizarResponse")
	public ResultFinalizar setFinalizar(
			@WebParam(name = "oFinalizar", targetNamespace = "http://wshr.mtc.gob.pe/") Finalizar oFinalizar);

	/**
	 * Finalizacion de Hoja Ruta por Empresa de Transporte.
	 *
	 * @param oFinalizar
	 * @return returns pe.gob.mtc.wshr.ResultFinalizar
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setFinalizar2")
	@WebResult(name = "setFinalizar2Result", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setFinalizar2", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetFinalizar2")
	@ResponseWrapper(localName = "setFinalizar2Response", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetFinalizar2Response")
	public ResultFinalizar setFinalizar2(
			@WebParam(name = "oFinalizar", targetNamespace = "http://wshr.mtc.gob.pe/") Finalizar2 oFinalizar);

	/**
	 * Registro de Hoja Ruta por Empresa de Transporte.
	 *
	 * @param oHojaRuta
	 * @return returns pe.gob.mtc.wshr.ResultHojaRuta
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setHojaRuta")
	@WebResult(name = "setHojaRutaResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setHojaRuta", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetHojaRuta")
	@ResponseWrapper(localName = "setHojaRutaResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetHojaRutaResponse")
	public ResultHojaRuta setHojaRuta(
			@WebParam(name = "oHojaRuta", targetNamespace = "http://wshr.mtc.gob.pe/") HojaRuta oHojaRuta);

	/**
	 * Registro de Manifiesto por Empresa de Transporte.
	 *
	 * @param oManifiesto
	 * @return returns pe.gob.mtc.wshr.ResultManifiesto
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setManifiesto")
	@WebResult(name = "setManifiestoResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setManifiesto", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetManifiesto")
	@ResponseWrapper(localName = "setManifiestoResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetManifiestoResponse")
	public ResultManifiesto setManifiesto(
			@WebParam(name = "oManifiesto", targetNamespace = "http://wshr.mtc.gob.pe/") Manifiesto oManifiesto);

	/**
	 * Registro de Tripulante por Empresa de Transporte.
	 *
	 * @param oTripulante
	 * @return returns pe.gob.mtc.wshr.ResultTripulante
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/setTripulante")
	@WebResult(name = "setTripulanteResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "setTripulante", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetTripulante")
	@ResponseWrapper(localName = "setTripulanteResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.SetTripulanteResponse")
	public ResultTripulante setTripulante(
			@WebParam(name = "oTripulante", targetNamespace = "http://wshr.mtc.gob.pe/") Tripulante oTripulante);

	/**
	 * Informacion de Pasajero por Embarque Biometrico.
	 *
	 * @param oBiometrico
	 * @return returns pe.gob.mtc.wshr.ResultBiometrico
	 */
	@WebMethod(action = "http://wshr.mtc.gob.pe/getBiometrico")
	@WebResult(name = "getBiometricoResult", targetNamespace = "http://wshr.mtc.gob.pe/")
	@RequestWrapper(localName = "getBiometrico", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetBiometrico")
	@ResponseWrapper(localName = "getBiometricoResponse", targetNamespace = "http://wshr.mtc.gob.pe/", className = "pe.gob.mtc.wshr.GetBiometricoResponse")
	public ResultBiometrico getBiometrico(
			@WebParam(name = "oBiometrico", targetNamespace = "http://wshr.mtc.gob.pe/") Biometrico oBiometrico);

}
